### PR TITLE
feat/chunk_store: verify chunk_store_root is workable in constructor

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/522)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chunk_store/chunk_store.rs, line 91 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLW5xGTgSFg9c7f6vG9:-KLW5xGTgSFg9c7f6vGA:1554624215) ([raw file](https://github.com/maidsafe/safe_vault/blob/b9d8de81a7bf029f9caeba46ab30a17b0fb44630/src/chunk_store/chunk_store.rs#L91)):*
> ```Rust
>             Err(e) => return Err(From::from(e)),
>         }
>         try!(Self::verify_workable(root.clone()));
> ```

Is that `clone` necessary? Couldn't `verify_workable` just take a `&PathBuf`?

---

*[src/chunk_store/chunk_store.rs, line 106 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLW674I2e3y6bB3oY9x:-KLW674I2e3y6bB3oY9y:1992501713) ([raw file](https://github.com/maidsafe/safe_vault/blob/b9d8de81a7bf029f9caeba46ab30a17b0fb44630/src/chunk_store/chunk_store.rs#L106)):*
> ```Rust
>                                                     .collect::<Vec<u8>>()
>                                                     .to_hex());
>         let value = rand::thread_rng().gen_iter().take(10).collect::<Vec<u8>>();
> ```

There's no reason to use random values here. Just `0`s would do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chunk_store/chunk_store.rs, line 29 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWFFdubAlbGQOXGQDF:-KLWFFdubAlbGQOXGQDG:-1734730659) ([raw file](https://github.com/maidsafe/safe_vault/blob/b97f52b14843fbcfe4c3b43c9ced17c187cc404e/src/chunk_store/chunk_store.rs#L29)):*
> ```Rust
> 
> /// The interval for print status log.
> const MAX_CHUNK_FILE_NAME_U8_LENGTH: usize = 52;
> ```

I think this should be the length in characters, not the length in bytes of the number whose hexadecimal representation the file name is.

---

*[src/chunk_store/chunk_store.rs, line 103 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWFB2V3ebbglEA28wp:-KLWFB2V3ebbglEA28wq:-165532614) ([raw file](https://github.com/maidsafe/safe_vault/blob/b97f52b14843fbcfe4c3b43c9ced17c187cc404e/src/chunk_store/chunk_store.rs#L103)):*
> ```Rust
>     }
> 
>     fn verify_workable(root: &PathBuf) -> Result<(), Error> {
> ```

Maybe `verify_file_creation` would be more descriptive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by maqi** [comment]
*[src/chunk_store/chunk_store.rs, line 29 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWFFdubAlbGQOXGQDF:-KLWO9_F5yr7F7rqwSHq:1847131133) ([raw file](https://github.com/maidsafe/safe_vault/blob/b97f52b14843fbcfe4c3b43c9ced17c187cc404e/src/chunk_store/chunk_store.rs#L29)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> I think this should be the length in characters, not the length in bytes of the number whose hexadecimal representation the file name is.
</details>
resolved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by maqi** [comment]
*[src/chunk_store/chunk_store.rs, line 103 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWFB2V3ebbglEA28wp:-KLWOE-U6KeUp-Q2ztPP:1847131133) ([raw file](https://github.com/maidsafe/safe_vault/blob/b97f52b14843fbcfe4c3b43c9ced17c187cc404e/src/chunk_store/chunk_store.rs#L103)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Maybe `verify_file_creation` would be more descriptive.
</details>
resolved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by Fraser999** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/chunk_store/chunk_store.rs, line 28 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWPyKJA0m4lPWbJN1Q:-KLWPyKKxkMtYEO5JfXy:-855331241) ([raw file](https://github.com/maidsafe/safe_vault/blob/25d7bfb7d9ffbfa4224e297d66aebd0e192660a2/src/chunk_store/chunk_store.rs#L28)):*
> ```Rust
> use rustc_serialize::hex::{FromHex, ToHex};
> 
> /// The interval for print status log.
> ```

copy-paste error?

---

*[src/chunk_store/chunk_store.rs, line 105 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWQ97S8GekSn0tZagz:-KLWQ97S8GekSn0tZah-:836417502) ([raw file](https://github.com/maidsafe/safe_vault/blob/25d7bfb7d9ffbfa4224e297d66aebd0e192660a2/src/chunk_store/chunk_store.rs#L105)):*
> ```Rust
>     fn verify_file_creation(root: &PathBuf) -> Result<(), Error> {
>         let bytes: Vec<u8> = vec![b'0'; MAX_CHUNK_FILE_NAME_LENGTH];
>         let file_path = root.join(String::from_utf8(bytes).expect("Found invalid UTF-8"));
> ```

We should be preferring `unwrap!` now I think.

---

*[src/chunk_store/chunk_store.rs, line 108 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWQG0jZPNAhzbeEjTQ:-KLWQG0jZPNAhzbeEjTR:-1838733706) ([raw file](https://github.com/maidsafe/safe_vault/blob/25d7bfb7d9ffbfa4224e297d66aebd0e192660a2/src/chunk_store/chunk_store.rs#L108)):*
> ```Rust
>         // Write the testing file.
>         try!(fs::File::create(&file_path)
>             .and_then(|file| file.sync_all() ));
> ```

I don't think we need the `sync_all()` if we're not writing to the file.  Also I'm not sure that the comments about adding and removing the file add much to just reading the code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by Fraser999** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/chunk_store/chunk_store.rs, line 105 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWQ97S8GekSn0tZagz:-KLWQphcr6YqmnzkKGQH:-1567072587) ([raw file](https://github.com/maidsafe/safe_vault/blob/25d7bfb7d9ffbfa4224e297d66aebd0e192660a2/src/chunk_store/chunk_store.rs#L105)):*
<details><summary><i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>
> We should be preferring `unwrap!` now I think.
</details>
Actually - we should be able to avoid unwrapping altogether.  We can collect a vector of chars into a `String` I think.  No need to do the `u8` vector and `from_utf8`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by afck** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/chunk_store/chunk_store.rs, line 105 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWQ97S8GekSn0tZagz:-KLWSc9hiVr266u-tIyF:352448815) ([raw file](https://github.com/maidsafe/safe_vault/blob/25d7bfb7d9ffbfa4224e297d66aebd0e192660a2/src/chunk_store/chunk_store.rs#L105)):*
<details><summary><i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>
> Actually - we should be able to avoid unwrapping altogether.  We can collect a vector of chars into a `String` I think.  No need to do the `u8` vector and `from_utf8`.
</details>
Right, `impl FromIterator<char> for String`, so something like `bytes.into_iter().collect()` should do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by maqi** [comment]
*[src/chunk_store/chunk_store.rs, line 108 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWQG0jZPNAhzbeEjTQ:-KLWT9btlovj6kBO2qxB:-1054325829) ([raw file](https://github.com/maidsafe/safe_vault/blob/25d7bfb7d9ffbfa4224e297d66aebd0e192660a2/src/chunk_store/chunk_store.rs#L108)):*
<details><summary><i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>
> I don't think we need the `sync_all()` if we're not writing to the file.  Also I'm not sure that the comments about adding and removing the file add much to just reading the code?
</details>
removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by maqi** [comment]
*[src/chunk_store/chunk_store.rs, line 105 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWQ97S8GekSn0tZagz:-KLWTFHtvG6YCkAelKiM:-389247215) ([raw file](https://github.com/maidsafe/safe_vault/blob/25d7bfb7d9ffbfa4224e297d66aebd0e192660a2/src/chunk_store/chunk_store.rs#L105)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Right, `impl FromIterator<char> for String`, so something like `bytes.into_iter().collect()` should do it.
</details>
is this acceptable? or still bytes.into_iter().collect() preferred ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by maqi** [comment]
*[src/chunk_store/chunk_store.rs, line 28 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWPyKJA0m4lPWbJN1Q:-KLWTRNNn-CYMt52R1Wr:-2086862044) ([raw file](https://github.com/maidsafe/safe_vault/blob/25d7bfb7d9ffbfa4224e297d66aebd0e192660a2/src/chunk_store/chunk_store.rs#L28)):*
<details><summary><i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>
> copy-paste error?
</details>
corrected

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chunk_store/chunk_store.rs, line 105 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/522#-KLWQ97S8GekSn0tZagz:-KLWU92bK8oEX7D8dOjs:-1968276470) ([raw file](https://github.com/maidsafe/safe_vault/blob/25d7bfb7d9ffbfa4224e297d66aebd0e192660a2/src/chunk_store/chunk_store.rs#L105)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> is this acceptable? or still bytes.into_iter().collect() preferred ?
</details>
This is even better - no need to allocate a slice first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/522)*

**Pull request merged**
