### PR TITLE
refactor/test suite Use mock crust only for tests 

### PR DESCRIPTION
**Pull request by dirvine**
Implements mock crust for tests as well as integration tests. 

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/456)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
*[a discussion](https://reviewable.io:443/reviews/maidsafe/safe_vault/456#-KGjwmdMAUDt3nx4YexG:-KGjwmdNBuVouOTad3H-:-449505640) (no related file):*
Seems now the tests in the persona.rs is actually `integration test` (i.e. network status can only be verified through whole nodes and client) , not `unit test`  anymore.
If we do need to get rid of the mock_routing,  I think better just remove all the current unit tests in the persona.rs and claim the current mock_crust tests  (or with some expansion) under the test folder (being the integration test) will do the job.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/456)*

**Comment by dirvine** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/maidsafe/safe_vault/456#-KGjwmdMAUDt3nx4YexG:-KGkKzPXjDoBLJfAXnBZ:906719757) (no related file):*
Yes I think a couple of these are possibly Integration tests. Then we have also a couple of unit tests (account_err and acccount_ok) as well as some behavioural tests (put_with_account and put_without_account)   The integration tests here are a bit of a misnomer as they require non API calls to complete, so more like behavioural tests in many ways. 

We can use ock crust to allow us to pass a routing object now and have much smaller unit tests as we move on, but for sure no large complex framework if at all possible. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/456)*

**Comment by dirvine** [comment]
Travis seems to have failed at elfutils for OS/X which seems weird 

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/456#-:-KGkN_rdPAbWAZiEkUvT:-1853773939)*

**Comment by afck** [comment]
Review status: 0 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/test_utils.rs, line 26 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/456#-KGkkSj2jtn5dpI13HWr:-KGkkSj2jtn5dpI13HWs:-1891781078) ([raw file](https://github.com/maidsafe/safe_vault/blob/279e8d3cd7ee2342b138789ad01cecc7c16a7edd/src/test_utils.rs#L26)):*
Typo: "random"
(But, yes, maybe this should just be inlined.)

---

*[src/mock_crust_detail/test_client.rs, line 74 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/456#-KGkkz8UCY2oY09cI7Id:-KGkkz8VGBcOJ5yXY8ip:1727757092) ([raw file](https://github.com/maidsafe/safe_vault/blob/279e8d3cd7ee2342b138789ad01cecc7c16a7edd/src/mock_crust_detail/test_client.rs#L74)):*
Typo: "client"

---

*[src/mock_crust_detail/test_node.rs, line 50 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/456#-KGkl9czKwPL5hCN_fLU:-KGkl9d-1ya24XADn6Id:-227986908) ([raw file](https://github.com/maidsafe/safe_vault/blob/279e8d3cd7ee2342b138789ad01cecc7c16a7edd/src/mock_crust_detail/test_node.rs#L50)):*
Typo: "queue"

---

*[src/personas/maid_manager.rs, line 399 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/456#-KGklrU1rjrRc9idcuak:-KGklrU1rjrRc9idcual:251149508) ([raw file](https://github.com/maidsafe/safe_vault/blob/279e8d3cd7ee2342b138789ad01cecc7c16a7edd/src/personas/maid_manager.rs#L399)):*
Should the last argument be `node_count`?

---

*[src/personas/maid_manager.rs, line 422 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/456#-KGkm-IpNmDTO4n8txvC:-KGkm-IpNmDTO4n8txvD:1969731997) ([raw file](https://github.com/maidsafe/safe_vault/blob/279e8d3cd7ee2342b138789ad01cecc7c16a7edd/src/personas/maid_manager.rs#L422)):*
Also `node_count`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/456)*

**Pull request merged**
