### PR TITLE
Expand CI scripts to automatically build and deploy release binaries ("rust-everywhere")

### PR DESCRIPTION
**Pull request by madadam**
Travis and AppVeyor will build and publish binaries to Github releases each time a version bump commit is pushed (a commit whose message look like "Version changed to x.y.z").

Currently builds binaries for these platforms:

- linux x86_64 (64bit)
- osx x86_64 (64bit)
- windows x86_64 (64bit)
- windows i686 (32bit)

More platforms may be added later.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/430)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/430)*

**Comment by dirvine** [comment]
@rossmuir  Can you check with Viv this looks good to go 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/430#-:-KFyXp6R0nEciymrQFFI:-1332561331)*

**Comment by rossmuir** [comment]
@madadam the branch is out-of-date with the base branch and needs rebased.
@dirvine I do not have privs to merge here, so I will assign in highfive to @Fraser999 
My only comment is that this update will bring this library out of sync with all the other libraries CI script-wise.

**Comment by madadam** [comment]
Closing in favor of https://github.com/maidsafe/safe_vault/pull/451

**Pull request closed without merging**
