### PR TITLE
WIP: Separate added and lost node handling.

### PR DESCRIPTION
**Pull request by afck**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/419)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
*[src/personas/pmid_manager.rs, line 151 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/419#-KFIDiMsQKqcZ5z4ZuEy:-KFIDiMsQKqcZ5z4ZuEz:1192759550) ([raw file](https://github.com/maidsafe/safe_vault/blob/adc9172bee95eb94c5a4cabe7dcfa5fd7caf84a2/src/personas/pmid_manager.rs#L151)):*
the ongoing_puts is an internal cache which won't get refreshed out during churn.
a new member of the PM group, will receive a put_failure response from a PN, but won't have the record in the cache.
So better forward that put_failure to DM, no matter the local cache has a record or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/419)*

**Comment by maqi** [comment]
*[src/personas/pmid_manager.rs, line 153 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/419#-KFIEPDdCek1aUJiiVHC:-KFIEPDdCek1aUJiiVHD:1850726022) ([raw file](https://github.com/maidsafe/safe_vault/blob/adc9172bee95eb94c5a4cabe7dcfa5fd7caf84a2/src/personas/pmid_manager.rs#L153)):*
not sure about why we are having this check here.
if routing works properly, when we receive a response, this check will always being true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/419)*

**Comment by maqi** [comment]
*[src/personas/structured_data_manager.rs, line 234 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/419#-KFIFVJIwo7CscoWH2QL:-KFIFVJJI9MHW3gpG-do:1304290785) ([raw file](https://github.com/maidsafe/safe_vault/blob/adc9172bee95eb94c5a4cabe7dcfa5fd7caf84a2/src/personas/structured_data_manager.rs#L234)):*
shall we put a comment here saying that the validity of the new data:
1, proper ownership of the content in the new data
2, the ownership of the new data is being correct to be descendant of the existing data
has been guaranteed via other methods, say the group consensus and routing validating

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/419)*

**Comment by maqi** [comment]
*[tests/mock_crust.rs, line 175 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/419#-KFIJ44gXmaxZl7xp7Zr:-KFIJ44hRjOYnxgRVuOm:1312175211) ([raw file](https://github.com/maidsafe/safe_vault/blob/adc9172bee95eb94c5a4cabe7dcfa5fd7caf84a2/tests/mock_crust.rs#L175)):*
build https://travis-ci.org/maidsafe/safe_vault/jobs/122839496 proves there is chance MORE copies of sd will be scattered across the network.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/419)*

**Comment by maqi** [comment]
*[tests/mock_crust.rs, line 95 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/419#-KFIJpxD6S67KrAJMMNl:-KFIJpxEkkSbMSmOSlW3:826812895) ([raw file](https://github.com/maidsafe/safe_vault/blob/adc9172bee95eb94c5a4cabe7dcfa5fd7caf84a2/tests/mock_crust.rs#L95)):*
replication of immutable_data may pickup three data_holders for a chunk (pickup two new ones after one data_holder becomes failed).
better change the assertion to be <=.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/419)*

**Comment by Fraser999** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/personas/pmid_manager.rs, line 151 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/419#-KFIDiMsQKqcZ5z4ZuEy:-KFIumS7oaka-Z4aHy6Z:226970500) ([raw file](https://github.com/maidsafe/safe_vault/blob/adc9172bee95eb94c5a4cabe7dcfa5fd7caf84a2/src/personas/pmid_manager.rs#L151)):*
This would leave us open to abuse from malicious PmidNodes though.  I think we should assess whether refreshing these caches is required or not, and if so, then we can plan and implement that.

---

*[src/personas/pmid_manager.rs, line 153 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/419#-KFIEPDdCek1aUJiiVHC:-KFIuWHpHf4Va6JRlI0S:-1466640985) ([raw file](https://github.com/maidsafe/safe_vault/blob/adc9172bee95eb94c5a4cabe7dcfa5fd7caf84a2/src/personas/pmid_manager.rs#L153)):*
True (barring edge cases).  I agree that this check should be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/419)*

**Comment by afck** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/personas/structured_data_manager.rs, line 234 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/419#-KFIFVJIwo7CscoWH2QL:-KFKjeVibEHwRs7UmAt1:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/adc9172bee95eb94c5a4cabe7dcfa5fd7caf84a2/src/personas/structured_data_manager.rs#L234)):*
Done.

---

*[tests/mock_crust.rs, line 175 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/419#-KFIJ44gXmaxZl7xp7Zr:-KFIcxHcLMOISG-MeJsH:-822368644) ([raw file](https://github.com/maidsafe/safe_vault/blob/adc9172bee95eb94c5a4cabe7dcfa5fd7caf84a2/tests/mock_crust.rs#L175)):*
With https://github.com/maidsafe/routing/pull/973 and our changes to `StructuredDataManager`, that shouldn't be the case anymore. But Travis still ran with the old Routing here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/419)*

**Comment by afck** [comment]
Replaced by #423

**Pull request closed without merging**
