### PR TITLE
feat/data_manager: send data ID in refresh, even if we don't have the data yet

### PR DESCRIPTION
**Pull request by afck**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/459)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGn5JVDunrqNtew9R8s:-KGn5JVDunrqNtew9R8t:-446984168) ([raw file](https://github.com/maidsafe/safe_vault/blob/e6ff32bacc282e79fe0a2de130cc1ca077513a0b/src/personas/data_manager.rs#L56)):*
I wonder if this should actually be the name and  `(version, sha512::hash)` then for SD we can request the actual data element when we want. IF everyone knew where the data was and it was at least in QUORUM nodes then they perhaps do not need to hold it unless it's requested by a client in a `Get` or `Post` message ?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGn5JVDunrqNtew9R8s:-KGp5zMTb_794G3hhEAd:1643661976) ([raw file](https://github.com/maidsafe/safe_vault/blob/e6ff32bacc282e79fe0a2de130cc1ca077513a0b/src/personas/data_manager.rs#L56)):*
That would be the first step back to a managed node model, wouldn't it?
But with the hash we'd again have the problem what to do if the response already contains a newer version of the structured data.
Let's discuss today whether we want to move in that direction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by maqi** [comment]
*[src/personas/maid_manager.rs, line 188 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv-ij2khTbKUdHC4ud:-KGv-ij3bJ81UDBlHdFu:-665848826) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/maid_manager.rs#L188)):*
is `accounts_to_delete` is the entries supposed to be removed from request_cache. if so, why not carry that check first, so here we don't need to carry out `close` check again (which is expensive) but a simple contains check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by afck** [comment]
Review status: 0 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 188 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv-ij2khTbKUdHC4ud:-KGv1-_49kFZbrDK1cw0:-839233132) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/maid_manager.rs#L188)):*
Since we're now given an actual `RoutingTable` and don't have to switch threads, it's not _that_ expensive anymore. So I went with this variant since it reduces the coupling between the two containers.
I don't feel strongly about it, though. If you like the other variant better, I'm happy to change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by maqi** [comment]
*[src/personas/maid_manager.rs, line 188 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv-ij2khTbKUdHC4ud:-KGv1lfAqWADZ9Uc0gjF:337038858) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/maid_manager.rs#L188)):*
i am just thinking if the `accounts_to_delete` does contains not much entries as claimed in the commit comment, a `contains` check shall be much cheaper than the close check (especially when the routing_table grows large)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by afck** [comment]
Review status: 0 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 188 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv-ij2khTbKUdHC4ud:-KGv7-WaIpKIEquA5UrQ:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/maid_manager.rs#L188)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by Fraser999** [comment]
Review status: 0 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/personas/data_manager.rs, line 230 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv6C8lWM88obJmPH01:-KGv6C8mv8WlzplT_1k8:-888599830) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/data_manager.rs#L230)):*
I guess I'd have used the new `count_removed_data()` function here for consistency's sake.

---

*[src/personas/maid_manager.rs, line 187 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv6y-_fdx3yEPLBRmA:-KGv6y-_fdx3yEPLBRmB:1878038) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/maid_manager.rs#L187)):*
`not_close(&&req.src.name()))` could be just `not_close(&req.src.name()))` I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by afck** [comment]
Review status: 0 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/personas/data_manager.rs, line 230 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv6C8lWM88obJmPH01:-KGv8nGt7RQ5a09wC7WH:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/data_manager.rs#L230)):*
Done.

---

*[src/personas/maid_manager.rs, line 187 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv6y-_fdx3yEPLBRmA:-KGv7fVN05STPH0sI32b:-1847112890) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/maid_manager.rs#L187)):*
No, because I used it also below where it needed that signature.
But I followed Qi's suggestion anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by dirvine** [comment]
Reviewed 2 of 4 files at r2, 18 of 19 files at r3, 1 of 2 files at r4, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by Fraser999** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 187 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv6y-_fdx3yEPLBRmA:-KGvABESLPjyH-G9Tusn:230864418) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/maid_manager.rs#L187)):*
I don't mean to change the signature of the closure, I just mean that `src.name()` already returns a reference, so we only need one `&` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by maqi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGvAgggrtBq4ejSyYHp:-KGvAgghzobXe2q4J6P5:-791689140) (no related file):*
just put a comment here as remind:
this new approach of `sending data_id even we don't have it` allows the test of `deletion under churn` to be passed.
however, this comes with a cost that for the new coming node, a sequence of get request and get_failure response has to be exchanged. Such messages are tiny so is acceptable so far.
no action needs to be taken to resolve this now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by afck** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGvAgggrtBq4ejSyYHp:-KGvC8iBaJYCu3onzyYs:311869617) (no related file):*
Yes, but I think that added traffic is negligible - those messages are small and it's better to keep the code simple.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by afck** [comment]
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/maid_manager.rs, line 187 \[r5\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/459#-KGv6y-_fdx3yEPLBRmA:-KGvECQfJZEIPsChZF_g:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/ba6a55156deba88feb47ef08b509e0598e1acfc0/src/personas/maid_manager.rs#L187)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by Fraser999** [comment]
Reviewed 2 of 4 files at r2, 18 of 19 files at r3, 1 of 2 files at r4, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Comment by maqi** [comment]
Reviewed 2 of 4 files at r2, 18 of 19 files at r3, 1 of 2 files at r4, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/459)*

**Pull request merged**
