### PR TITLE
some logs for debugging

### PR DESCRIPTION
**Pull request by maqi**
This change is [Review on Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/363)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Fraser999** [comment]
I'm not sure about a lot of these Qi.  It looks like many will be pretty much just duplicating the trace message from the event loop in `vault::do_run`.  The only use I could see for these would be to check the demuxing is working properly in `vault::on_...`, so they'd be temporary only - not committed to the repo.

I think the ones which are showing how we're responding are potentially useful.

Can you keep the format consistent though please - we have some that have "SDM" and others have "StructuredDataManager" - I guess shorter is better for logging?

**Comment by maqi** [comment]
removed some duplicated logging and making the pattern consistent (MM, SDM and PM)

**Comment by Fraser999** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/363)*

**Pull request merged**
