### PR TITLE
fix/vault: fix restart issue.

### PR DESCRIPTION
**Pull request by Fraser999**
This fixes an issue where restarting the routing instance did not delete the existing instance,
causing the vault to connect to itself.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/441)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/441)*

**Comment by dirvine** [comment]
r? 'dirvine

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/441#-:-KGM9kkUDPONrXkGUyn7:-462889410)*

**Comment by dirvine** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/441)*

**Comment by dirvine** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/441)*

**Pull request merged**
