### PR TITLE
feat/chunk_store: chunk_store path handling cleanup

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/510)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/vault.rs, line 96 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/510#-KLHHLBcFI5-M-OurzcF:-KLHHLBdiYBg26COCRa9:-136279235) ([raw file](https://github.com/maidsafe/safe_vault/blob/e69fb80a90de22b73fce4b61dbe8fc80e651e651/src/vault.rs#L96)):*
> ```Rust
>         } else {
>             let path_str = config.chunk_store_root.unwrap();
>             let root_path = Path::new(&path_str);
> ```

As discussed, `CHUNK_STORE_DIR` should probably be appended in both cases: If `path_str` is `/tmp`, we must not delete and recreate that directory in `reset_store`.

---

*[src/chunk_store/chunk_store.rs, line 87 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/510#-KLHC-Q3h1HlZ-7sFUcT:-KLHC-Q4ulDhVRjx8y8I:875256630) ([raw file](https://github.com/maidsafe/safe_vault/blob/1807ef6b24f4acca9fda2a58ee6f196b67715288/src/chunk_store/chunk_store.rs#L87)):*
> ```Rust
>             // fs::create_dir_all. A re-attempt needs to be carried out in that case.
>             Err(ref e) if e.kind() == ErrorKind::AlreadyExists => {
>                 match fs::create_dir_all(&root) {
> ```

Why could this work now, after it has already failed once with the same `root`?

---

*[src/chunk_store/chunk_store.rs, line 198 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/510#-KLHGySqDPW49FZqVc6-:-KLHGySqDPW49FZqVc60:1612716245) ([raw file](https://github.com/maidsafe/safe_vault/blob/1807ef6b24f4acca9fda2a58ee6f196b67715288/src/chunk_store/chunk_store.rs#L198)):*
> ```Rust
>             Ok(_) => {}
>             Err(e) => return Err(From::from(e)),
>         }
> ```

Isn't this the same as `try!(fs::remove_dir_all(&self.rootdir))`? (Also below.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/510)*

**Comment by maqi** [comment]
*[src/chunk_store/chunk_store.rs, line 87 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/510#-KLHC-Q3h1HlZ-7sFUcT:-KLHP6PlEhZncCY4qG7B:1178082078) ([raw file](https://github.com/maidsafe/safe_vault/blob/1807ef6b24f4acca9fda2a58ee6f196b67715288/src/chunk_store/chunk_store.rs#L87)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Why could this work now, after it has already failed once with the same `root`?
</details>
as explained in the comments, the multiple concurrent execution may cause the second instance failing first but will succeed on second attempt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/510)*

**Comment by maqi** [comment]
*[src/chunk_store/chunk_store.rs, line 198 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/510#-KLHGySqDPW49FZqVc6-:-KLHVlV_O5EOnvQDao7L:1847131133) ([raw file](https://github.com/maidsafe/safe_vault/blob/1807ef6b24f4acca9fda2a58ee6f196b67715288/src/chunk_store/chunk_store.rs#L198)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Isn't this the same as `try!(fs::remove_dir_all(&self.rootdir))`? (Also below.)
</details>
resolved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/510)*

**Comment by maqi** [comment]
*[src/vault.rs, line 96 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/510#-KLHHLBcFI5-M-OurzcF:-KLHViNUvNcxekpEhiZB:1847131133) ([raw file](https://github.com/maidsafe/safe_vault/blob/e69fb80a90de22b73fce4b61dbe8fc80e651e651/src/vault.rs#L96)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> As discussed, `CHUNK_STORE_DIR` should probably be appended in both cases: If `path_str` is `/tmp`, we must not delete and recreate that directory in `reset_store`.
</details>
resolved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/510)*

**Comment by afck** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/510)*

**Pull request merged**
