### PR TITLE
Support appendable data

### PR DESCRIPTION
**Pull request by Fraser999**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/547)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 4 of 7 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 650 at r3](https://reviewable.io:443/reviews/maidsafe/safe_vault/547#-KRSYrBQyUGb0yNX8Wmd:-KRSYrBRD7Jx8tH9ebpQ:b13deo1) ([raw file](https://github.com/maidsafe/safe_vault/blob/aec23c8687ce878ebde526dea468daf297e48b1e/src/personas/data_manager.rs#L650)):*
> ```Rust
>                         if let Data::PubAppendable(ref mut received) = data {
>                             received.data =
>                                 appendable_data.data.union(&received.data).cloned().collect();
> ```

`received.data.extend(appendable_data.data)` would probably cause less allocation. (Also below.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/547)*

**Comment by Fraser999** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 650 at r3](https://reviewable.io:443/reviews/maidsafe/safe_vault/547#-KRSYrBQyUGb0yNX8Wmd:-KRSbz1dL1-AqQSbYYqV:b8nhoqr) ([raw file](https://github.com/maidsafe/safe_vault/blob/aec23c8687ce878ebde526dea468daf297e48b1e/src/personas/data_manager.rs#L650)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> `received.data.extend(appendable_data.data)` would probably cause less allocation. (Also below.)
</details>
Good point.  Any preference between `extend()` and `append()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/547)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 650 at r3](https://reviewable.io:443/reviews/maidsafe/safe_vault/547#-KRSYrBQyUGb0yNX8Wmd:-KRSgGz601EITRcKk-93:bhksu60) ([raw file](https://github.com/maidsafe/safe_vault/blob/aec23c8687ce878ebde526dea468daf297e48b1e/src/personas/data_manager.rs#L650)):*
<details><summary><i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>
> Good point.  Any preference between `extend()` and `append()`?
</details>
I think that shoudn't matter, as consuming `appendable_data` is fine here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/547)*

**Comment by Fraser999** [comment]
Reviewed 4 of 7 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/547)*

**Pull request merged**
