### PR TITLE
feat/deploy: pull the config files from the release-config repo

### PR DESCRIPTION
**Pull request by madadam**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/486)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Fraser999** [comment]
Shouldn't [deploy_docker_image.sh](https://github.com/maidsafe/safe_vault/blob/master/ci/travis/deploy_docker_image.sh) be updated too?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/486#-:-KKD-guWjLk55ENRWkmH:2102983477)*

**Comment by madadam** [comment]
I guess it should :) Good catch!

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/486#-:-KKD0_rESddQhab3qTLJ:-2054490955)*

**Comment by Fraser999** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/486)*

**Pull request merged**
