### PR TITLE
DM update to handle other data types.

### PR DESCRIPTION
**Pull request by Fraser999**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/398) &emsp; Multiple assignees:&emsp;@brian-js&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/brian-js">brian-js</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/dirvine">dirvine</a>,&emsp;@maqi&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/maqi">maqi</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Fraser999** [comment]
+@dirvine +@maqi +@brian-js 

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-:-KEGa12JTcC04vd_Zfyx:1762688415)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 146 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEGiS9MhlxeUGSay8B4:-KEGiS9NsYDBCkso4-5s:678169830) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L146)):*
flow doc Get ImmutableData flow 4.f indicates the fetching from Backup/Sacrificial to other two types is not required, is it?
Also, will do so causing a circular loop in case of all fails?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/vault.rs, line 264 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEGu54XRHmvBd4c241-:-KEGu54XRHmvBd4c2410:-447467991) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/vault.rs#L264)):*
this combination makes the code in handle_get_success quite complicated.
Will the DM->DM get_success to be handled by a separate handle_get_from_other_location_success make the code cleaner?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 376 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEGwNnUDC_lmCOb2EG_:-KEGwNnUDC_lmCOb2EGa:939264818) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L376)):*
say a get_success from PN to DM holding a backup_copy,
the later on replication procedure requires the backup_copy,
but the later on send_get_success needs a normal_copy,
is it a problem?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 1070 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEGzoTzgHWMsqSf4PgR:-KEGzoU-ZAo29CtnIqut:583902852) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1070)):*
the `clients` shall be better changed to requester, as the IDM(normal) may also asking for the backup/sacrificial copies.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 1074 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEH0EW6KMxnBWKD4T5j:-KEH0EW7S0a1Ao_PcNKa:642958690) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1074)):*
if the fetching from Backup/Sacrificial to other two types is not required, here shall return.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 633 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEH75wOUKgTmLIEDZ25:-KEH75wPtLT6zdkP6e8R:-243236056) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L633)):*
same as the handle_success function, will DM->DM get_success response to be handled by a separate function call from Vault to make code cleaner?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 149 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHA7L_wdqQks9c1aGz:-KEHA7L_wdqQks9c1aH-:-62342070) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L149)):*
there will be two get_flow bearing the same message_id happening at the same time,
shall the message_id to be increased here, like what we do to the put, as well?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 1280 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHDRopNEyoF2pCmK30:-KEHDRoq6-fVBR3lRArE:-244981300) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1280)):*
shall this panic say something?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 1495 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHGyYpAEKN6XQ-yGpt:-KEHGyYqtR2S_3GaKGaH:-1924043117) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1495)):*
shall be `The Backup holder ...`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 1595 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHK6PFiJUjGdY7USB_:-KEHK6PFiJUjGdY7USBa:1996026704) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1595)):*
The previous REPLICANTS is 4, which means will have 2 churn up and 2 churn down during the test
But now only 1 for each. will that be too less to stress the code?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 991 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHSeY5XXjWl1yh_2Dt:-KEHSeY5XXjWl1yh_2Du:-1087919747) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L991)):*
this comment is no longer consistent with the new implementation

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by Fraser999** [comment]
Review status: 0 of 12 files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[src/vault.rs, line 264 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEGu54XRHmvBd4c241-:-KEHRo1V2ThABZn7I5HG:-1970652644) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/vault.rs#L264)):*
I considered that, but don't think it's worthwhile.  The failure case is pretty different between the PN and DM sending it. But the only difference for the success case is https://github.com/Fraser999/safe_vault/blob/idm_update/src/personas/immutable_data_manager.rs#L391-L405

---

*[src/personas/immutable_data_manager.rs, line 146 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEGiS9MhlxeUGSay8B4:-KEHSOHJjNadC24Hy234:-388085530) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L146)):*
The flow isn't meant to stop at 4.f.  Not sure if I can make that clearer in the docs, but at other places where the flow stops before the end, it says something like "finished flow".

It shouldn't cause infinite Gets either because of 5.b in the doc.

---

*[src/personas/immutable_data_manager.rs, line 149 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHA7L_wdqQks9c1aGz:-KEHW4CZSFaQTQgmPc1T:353454961) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L149)):*
I wanted to avoid that since I don't think it's a big issue now that the DM groups are defined by Xoring rather than hashing.  It's debatable though.

---

*[src/personas/immutable_data_manager.rs, line 376 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEGwNnUDC_lmCOb2EG_:-KEHZAfnbHXNkxVBMQiu:1293571819) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L376)):*
I don't think so (although these kind of questions would be a lot easier to answer if we had time to do comprehensive unit tests).  If we've got a backup copy in the `ongoing_get` cache, it means we were either asked for a backup copy by a client or other DM group, or a churn event has triggered it and we're a backup manager.

If we have to send a Normal copy later, that will only be because we've been asked for a Normal copy, and the entry won't be found because it's got a different name.

However, depending on how often that happens it might be worth checking for ongoing Backup or Sacrificial entries.  I wouldn't do that before profiling though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 146 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEGiS9MhlxeUGSay8B4:-KEHdiXh8NHNDwrr12K5:-433823713) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L146)):*
Ah, i think when the flow doc was written, it was assumed get backup/sacrificial from client is not allowed. and section 4 was mainly cover the situation of DM handling CLIENT request. so 4.f doesn't make it clear.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by maqi** [comment]
*[src/personas/immutable_data_manager.rs, line 149 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHA7L_wdqQks9c1aGz:-KEHfEmf7yqVGe7mP4QZ:852360971) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L149)):*
not sure whether Xoring or hashing matters here.
I think the only concern is whether there is any accumulator using message_id as the sole key to differentiate the msg.
The test network will definitely having one vault handling more than one flow at the same time.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by brian-js** [comment]
*[src/timed_buffer.rs, line 72 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KERnuh6PAeRE-kzCoNM:-KERnuh6PAeRE-kzCoNN:2053324716) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/timed_buffer.rs#L72)):*
This is still only used in tests, so since it wasn't required before it's not required now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by brian-js** [comment]
*[src/personas/immutable_data_manager.rs, line 315 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KERpXHhRV816RvKD-Hm:-KERpXHi-94SXJJzXL2j:-1988023722) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/personas/immutable_data_manager.rs#L315)):*
I don't think this is required now since there's no timeout at the MM waiting for it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by brian-js** [comment]
*[src/personas/immutable_data_manager.rs, line 605 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEVfHSyUkyz7n6ILJs3:-KEVfHSyUkyz7n6ILJs4:-750249801) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/personas/immutable_data_manager.rs#L605)):*
It's a bit odd inserting an entry just removed in order to satisfy a further function call. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by Fraser999** [comment]
Review status: 0 of 14 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/timed_buffer.rs, line 72 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KERnuh6PAeRE-kzCoNM:-KEVc-5Y2pddgIlbd_f8:1072573285) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/timed_buffer.rs#L72)):*
It's now used in a test which isn't in the same mod, so it is required now.  Perhaps that test could be refactored to avoid needing to know the length, but I wanted to avoid more changes than necessary since this PR is already huge.

---

*[src/personas/immutable_data_manager.rs, line 149 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHA7L_wdqQks9c1aGz:-KEW794uYSlYgwvbYI8L:753907564) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L149)):*
OK - I agree that we should err on the side of safety.  I'll update the PR - just need to check that I'm not going to mess the flow up with this change.

---

*[src/personas/immutable_data_manager.rs, line 633 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEH75wOUKgTmLIEDZ25:-KEW4B3fxDi8qDVyLrVN:-2092761175) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L633)):*
Same answer as before - I don't think it helps.

---

*[src/personas/immutable_data_manager.rs, line 991 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHSeY5XXjWl1yh_2Dt:-KEW4Req1rOaHZNICFKo:-839412938) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L991)):*
It is - that function does what the comment says, which is the correct flow I think.

---

*[src/personas/immutable_data_manager.rs, line 1070 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEGzoTzgHWMsqSf4PgR:-KEW5E-t4eUmsy5SEZd6:1936806298) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1070)):*
True - I'll fix that.

---

*[src/personas/immutable_data_manager.rs, line 1074 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEH0EW6KMxnBWKD4T5j:-KEW5TH7c4dkvshyiJJh:905152802) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1074)):*
I think we *do* want to recover for all types though.

---

*[src/personas/immutable_data_manager.rs, line 1280 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHDRopNEyoF2pCmK30:-KEW683H6koK_bCyGYuG:-1353031029) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1280)):*
I don't see much point really.  If it trips, we'll get the line number and the `if` which caused it is pretty basic - we expected the `dst` to be a `NodeManager` and it wasn't.

---

*[src/personas/immutable_data_manager.rs, line 1495 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHGyYpAEKN6XQ-yGpt:-KEW6_gJ8XdJQK5yiwMH:-1385866102) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1495)):*
Well spotted.

---

*[src/personas/immutable_data_manager.rs, line 1595 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEHK6PFiJUjGdY7USB_:-KEW6kO1EGeNCau_QUQv:-2145901389) ([raw file](https://github.com/maidsafe/safe_vault/blob/e46aaa614e51a5efc0c80d3403acd3527ec8795e/src/personas/immutable_data_manager.rs#L1595)):*
The tests were passing for me, but you could be right.  I'd rather leave them alone for now unless we see a problem in the test results.  Then we can concentrate on the larger integration tests and revisit these later.

---

*[src/personas/immutable_data_manager.rs, line 315 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KERpXHhRV816RvKD-Hm:-KEW--fIgFTjB9_qXegW:-1663314500) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/personas/immutable_data_manager.rs#L315)):*
With the current flow, we still need to send the response so that the MM can respond to the Client.  Once we implement the ability for the MM to be told by Vaults the ratio of Sacrificial data, we will update this.

---

*[src/personas/immutable_data_manager.rs, line 605 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KEVfHSyUkyz7n6ILJs3:-KEW3pJXgatof2_UiCmz:2063558600) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/personas/immutable_data_manager.rs#L605)):*
True - I'll swap the `remove`/`insert` for `get_mut`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by brian-js** [comment]
*[src/personas/immutable_data_manager.rs, line 315 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KERpXHhRV816RvKD-Hm:-KEWZMZEKKX-yR7p970O:-2093511598) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/personas/immutable_data_manager.rs#L315)):*
The MM could respond with success until then I guess. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by Fraser999** [comment]
Review status: 0 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/personas/immutable_data_manager.rs, line 315 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KERpXHhRV816RvKD-Hm:-KEW_PD2ZYonYdWzTlld:-68491151) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/personas/immutable_data_manager.rs#L315)):*
I don't really want to increase this commit with further changes to the flow when these can all go in a single smaller one (especially workaround changes).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by brian-js** [comment]
*[src/personas/immutable_data_manager.rs, line 315 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KERpXHhRV816RvKD-Hm:-KEWaTAIZYfTNKWkt6QZ:-691760033) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/personas/immutable_data_manager.rs#L315)):*
It's not intended as a workaround the code was there to satisfy the premise that when the data reaches the DM it can be considered stored, I don't think that's regarded as valid interpretation anymore, but I agree it can be changed later.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by dirvine** [comment]
Review status: 0 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/personas/immutable_data_manager.rs, line 315 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-KERpXHhRV816RvKD-Hm:-KEWh1O_ejcw3kQR-yn0:-468585903) ([raw file](https://github.com/maidsafe/safe_vault/blob/2275bceb072894669aeb545749cf762f8b792777/src/personas/immutable_data_manager.rs#L315)):*
Yes best to think of this guarantee as "if the data reaches the DM it can be considered *will be stored*" 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by dirvine** [comment]
Reviewed 1 of 5 files at r2.
Review status: 0 of 14 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by brian-js** [comment]
Reviewed 8 of 12 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: 13 of 14 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by brian-js** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398)*

**Comment by dirvine** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/398#-:-KEWxWvtu9t4dIu8mHEO:1417088721)*

**Pull request merged**
