### PR TITLE
Enable mock crust for testing

### PR DESCRIPTION
**Pull request by madadam**
Changes to support testing with mock crust. Includes a minimal mock-crust enabled test.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/394)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
*[Cargo.toml, line 33 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KECLt9VRTfRQKho3oO8:-KECLt9W6J0NrjwEsw1s:-1682170008) ([raw file](https://github.com/maidsafe/safe_vault/blob/7c20e8ecdac4f8d34f0014375e7e9c797528e5f3/Cargo.toml#L33)):*
is dependent to that safe_core still required? seems the testing_client is now wrapping around routing_client directly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Comment by maqi** [comment]
Will it be more suitable to move src\tests.rs to src\tests, and make TestClient, TestNode and tests separate files, to allow convenient expanding let on?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-:-KECNXqtJKaNKLgcw7aT:-873514643)*

**Comment by madadam** [comment]
Sure, sounds like a good idea.

**Comment by maqi** [comment]
*[src/tests.rs, line 228 \[r4\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KECRK6PmSsDlqntvQIM:-KECRK6PmSsDlqntvQIN:1935045183) ([raw file](https://github.com/maidsafe/safe_vault/blob/7c20e8ecdac4f8d34f0014375e7e9c797528e5f3/src/tests.rs#L228)):*
the CI network_test using 1KB as typical testing data. shall we use 1KB random content here as well?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Comment by Fraser999** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/vault.rs, line 63 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWdAc9DFkOP5MATEvs:-KEWdAc9DFkOP5MATEvt:-683412583) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/vault.rs#L63)):*
Can we stick with the more explicit convention of `_sender` and `_receiver` for channels throughout this PR please?

---

*[src/vault.rs, line 146 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWcOEvr14GmSaPt8ls:-KEWcOEvr14GmSaPt8lt:1373034004) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/vault.rs#L146)):*
Can `unwrap()` be changed to `expect()` here please?

---

*[src/vault.rs, line 164 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWccndtCLwUTO_j9Jy:-KEWccndtCLwUTO_j9Jz:-625098621) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/vault.rs#L164)):*
Can `unwrap()` be changed to `unwrap_result!()` here please?

---

*[src/tests/mod.rs, line 18 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWeFXsfuLnfPyS7uxZ:-KEWeFXteXa3XRkEhCbO:2060135982) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/tests/mod.rs#L18)):*
This should have the standard set of lint levels set as found in main.rs, including the Clippy ones.

---

*[src/tests/mod.rs, line 41 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWfx4btAzbvN64mihr:-KEWfx4btAzbvN64mihs:-2074272357) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/tests/mod.rs#L41)):*
Could we just use [the existing helper function](https://github.com/maidsafe/safe_vault/blob/master/src/utils.rs#L30-L34)?

---

*[src/tests/mod.rs, line 49 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWgIZ3QR8fA7-EsMYM:-KEWgIZ3QR8fA7-EsMYN:-1333523501) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/tests/mod.rs#L49)):*
These types of comparison between large(ish) arrays yield better failure messages if we use `assert!(data.value() == orig_data.value())` since the entire contents of both arrays isn't printed.

---

*[src/tests/mod.rs, line 52 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWfui9EsTBo2aoVPb2:-KEWfui9EsTBo2aoVPb3:1328779608) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/tests/mod.rs#L52)):*
Please rename `d` to something meaningful.

---

*[src/tests/test_client.rs, line 101 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWeyB2JrFMwP18BNbV:-KEWeyB2JrFMwP18BNbW:778914375) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/tests/test_client.rs#L101)):*
Please rename `r` to something meaningful.  Same for instance in `put` below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Comment by dirvine** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/vault.rs, line 164 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWccndtCLwUTO_j9Jy:-KEWjptSxbGUcQnvGpLg:1802051243) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/vault.rs#L164)):*
unwrap_result in a test is also not useful, expect with a clear message is better and requires  no additional crates. Spandan Fraser and I had a convo about this. Test should be small and expect aborts with the correct message clearly showing where the failure was 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Comment by Fraser999** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/vault.rs, line 164 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWccndtCLwUTO_j9Jy:-KEWmroI7HNxJQfYncMW:-338014599) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/vault.rs#L164)):*
I disagree with this, but need to reply to make reviewable happy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Comment by madadam** [comment]
Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/vault.rs, line 146 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWcOEvr14GmSaPt8ls:-KEWrFb8iGF28IhREHtB:1946685287) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/vault.rs#L146)):*
The error can only happen when the mutex becomes poisoned (which means that some other thread panicked while holding it) and the panic message would already contain that information. Not sure an explicit expect message would add anything useful here. Besides, we keep using `mutex.lock().unwrap()` all over the place, so I'd say it's become a common practice.

---

*[src/vault.rs, line 164 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWccndtCLwUTO_j9Jy:-KEWxn5oEM_YTM_X-IgV:-584801355) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/vault.rs#L164)):*
See my previous comment (for line 146) for my opinion on this.

---

*[src/tests/mod.rs, line 18 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWeFXsfuLnfPyS7uxZ:-KEWujrpsUkZbHwq3yaS:-781818711) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/tests/mod.rs#L18)):*
`main.rs` has `#![cfg_attr(feature = "use-mock-crust", allow(unused))]
` otherwise it keeps complaining about unused stuff when compiled with `use-mock-crust`. So I explicitly deny it here again. But I'm open to suggestions how to solve this problem more elegantly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Comment by Fraser999** [comment]
Review status: 0 of 9 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/vault.rs, line 146 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWcOEvr14GmSaPt8ls:-KEX1xSWU42qc0X7RM7x:-1484500826) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/vault.rs#L146)):*
I agree, but Clippy complains about bare `unwrap`s and recommends `expect`.  We also have a policy to not use bare `unwrap`s, so there shouldn't be any instances of these in our code.

---

*[src/vault.rs, line 164 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWccndtCLwUTO_j9Jy:-KEX2G6GfUdUglhJQVzf:1427381797) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/vault.rs#L164)):*
This one is less defensible since it's not locking a mutex, but regardless, the policy is to not use `unwrap`s.

---

*[src/tests/mod.rs, line 18 \[r6\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/394#-KEWeFXsfuLnfPyS7uxZ:-KEX2aKKtUGZOZQ9wS4g:1500760839) ([raw file](https://github.com/maidsafe/safe_vault/blob/aaeab76123fa1794b5cbcdc378bc395dc0f405a9/src/tests/mod.rs#L18)):*
Ah - sorry - my mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Comment by Fraser999** [comment]
Reviewed 1 of 4 files at r1, 3 of 5 files at r5, 2 of 3 files at r6, 4 of 4 files at r7.
Review status: 4 of 9 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Comment by Fraser999** [comment]
Reviewed 5 of 5 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Comment by Fraser999** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/394)*

**Pull request merged**
