### PR TITLE
Reduced timeout for PM put_request cache in test.

### PR DESCRIPTION
**Pull request by Fraser999**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/379)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Why does this timeout exist? Are we not guaranteed a response otherwise something else is wrong?

**Comment by Fraser999** [comment]
No, this is the timeout which was agreed to in the PMs for Put requests.  We need it in case the PN doesn't respond to a Put.  It's also used to clear entries out of the `ongoing_puts` map which won't resolve since we've been pushed out of the close group for that PN due to churn.

**Comment by maqi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/379)*

**Pull request merged**
