### PR TITLE
Verify kademlia invariant

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/487)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mock_crust_detail/mod.rs, line 88 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/487#-KKCfP5l7nWEJoYxjklx:-KKCfP5mzu2ATrLBejs-:1666815882) ([raw file](https://github.com/maidsafe/safe_vault/blob/a92303e7285280cd0191d9c23454f699df9ad0d6/src/mock_crust_detail/mod.rs#L88)):*
> ```Rust
> 
> /// Verify that the kademlia invariant is upheld for all nodes.
> pub fn verify_kademlia_invariant_for_all_nodes(nodes: &[TestNode]) {
> ```

It looks like we're _only_ calling the `all_nodes` variant. So it would probably make sense to _only_ expose a `verify_kademlia_invariant(tables: &[RoutingTable<XorName>])` from routing's side; then all that needs to be added on top of that in both routing and safe_vault is a method that maps the `TestNode`s to `RoutingTable<XorName>`s and then calls this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/487)*

**Comment by maqi** [comment]
*[src/mock_crust_detail/mod.rs, line 88 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/487#-KKCfP5l7nWEJoYxjklx:-KKD1fpYAqafxm1Q56lX:-229818471) ([raw file](https://github.com/maidsafe/safe_vault/blob/a92303e7285280cd0191d9c23454f699df9ad0d6/src/mock_crust_detail/mod.rs#L88)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> It looks like we're _only_ calling the `all_nodes` variant. So it would probably make sense to _only_ expose a `verify_kademlia_invariant(tables: &[RoutingTable<XorName>])` from routing's side; then all that needs to be added on top of that in both routing and safe_vault is a method that maps the `TestNode`s to `RoutingTable<XorName>`s and then calls this one.
</details>
changed to exposing as &[RoutingTable<XorName>]
resolved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/487)*

**Comment by afck** [comment]
Reviewed 2 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/487)*

**Pull request closed without merging**
