### PR TITLE
feat/refresh_delete: DM sending refresh on deletion

### PR DESCRIPTION
**Pull request by maqi**
data_mamager sending deletion refresh to prevent zombie data.
the disabled churn_delete test is now enabled and passed.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/452)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-KGWupQVZVvTGUQ4aQpf:-KGWupQWwiw3RJZG2vP6:1572114171) ([raw file](https://github.com/maidsafe/safe_vault/blob/4e83d460b06deba211bea4f7b43ae3f2946853bc/src/personas/data_manager.rs#L47)):*
That's `u64::MAX`.
(But maybe it would be cleaner to use an `Option`, so that `None` means "deleted"? Not sure ...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-KGWupQVZVvTGUQ4aQpf:-KGWxG4cvElugZsqlQ9k:-2030725190) ([raw file](https://github.com/maidsafe/safe_vault/blob/4e83d460b06deba211bea4f7b43ae3f2946853bc/src/personas/data_manager.rs#L47)):*
this is to be consistent with the current data_list format of IdAndVersion, which has to be a u64 instead of an Option.   :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by afck** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-KGWupQVZVvTGUQ4aQpf:-KGWzP2UXamZOKOpIqcB:-424192725) ([raw file](https://github.com/maidsafe/safe_vault/blob/4e83d460b06deba211bea4f7b43ae3f2946853bc/src/personas/data_manager.rs#L47)):*
But `u64::MAX` would still be cleaner than what looks like a magic number, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-KGWupQVZVvTGUQ4aQpf:-KGX-ocSKSTZ3gUkzIyR:-1389097621) ([raw file](https://github.com/maidsafe/safe_vault/blob/4e83d460b06deba211bea4f7b43ae3f2946853bc/src/personas/data_manager.rs#L47)):*
Apart from this - all looks good to me 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-KGWupQVZVvTGUQ4aQpf:-KGX0DE7vQUCUI-k8FEI:-945722796) ([raw file](https://github.com/maidsafe/safe_vault/blob/4e83d460b06deba211bea4f7b43ae3f2946853bc/src/personas/data_manager.rs#L47)):*
sure, I will change it to u64::MAX  
my above reply is just to your Option comment  :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-KGWupQVZVvTGUQ4aQpf:-KGX7NudhbYNJe7O_RpO:-2012666969) ([raw file](https://github.com/maidsafe/safe_vault/blob/4e83d460b06deba211bea4f7b43ae3f2946853bc/src/personas/data_manager.rs#L47)):*
using `u64::MAX` will having error `no associated item named `MAX` found for type `u64` in the current scope`.
so have to use `::std::u64::MAX` here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by afck** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-KGWupQVZVvTGUQ4aQpf:-KGX8FhHv1s1eeF3jhCo:-542298440) ([raw file](https://github.com/maidsafe/safe_vault/blob/4e83d460b06deba211bea4f7b43ae3f2946853bc/src/personas/data_manager.rs#L47)):*
Or `use std::u64;`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-KGWupQVZVvTGUQ4aQpf:-KGXDwzj-4XetxQepiLK:378556092) ([raw file](https://github.com/maidsafe/safe_vault/blob/4e83d460b06deba211bea4f7b43ae3f2946853bc/src/personas/data_manager.rs#L47)):*
yip `use std::u64`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 47 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-KGWupQVZVvTGUQ4aQpf:-KGXE3UPJAo_y5NftEsi:5174689) ([raw file](https://github.com/maidsafe/safe_vault/blob/4e83d460b06deba211bea4f7b43ae3f2946853bc/src/personas/data_manager.rs#L47)):*
ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by dirvine** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452)*

**Comment by dirvine** [comment]
r? @afck 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/452#-:-KGmM2I4vSfIzCHzppk1:1914605633)*

**Comment by maqi** [comment]
the work has now been covered in the PR https://github.com/maidsafe/safe_vault/pull/459

**Pull request closed without merging**
