### PR TITLE
Remove private_no_mangle_*, and update rust_sodium dep

### PR DESCRIPTION
**Pull request by Luke-Nukem**
`private_no_mangle_fns` and `private_no_mangle_statics` are removed in rust 1.31+.

I didn't realise I had auto rustfmt enabled in vim so it seems a little reformatting happened on save. If this is a problem let me know and I'll edit the commit involved.

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @Fraser999 (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by pierrechevalier83** [comment]
Hi @Luke-Nukem, thanks for your contribution :smile:

The first commit is covered in PR 170. Is there a particular reason why you would like to update the minimum required version of `rust_sodium`? (Note that ~0.10.0 allows 0.10.1)

**Comment by pierrechevalier83** [comment]
Hi @Luke-Nukem, I'm sorry you seem to have spent some time doing work that was also done in PR 670. It is now merged into master. Is there anything from this PR that you would like to keep on top of the latest master?

**Comment by Luke-Nukem** [comment]
I must be going blind... I could have sworn I looked at the PR's and didn't see that one.

There's some things in there I can add to, like the [`macro_use`](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html#macros) parts in `lib.rs`

```
-#[macro_use]
-extern crate unwrap;
```
I'll rebase on to this master tomorrow and remove any miscellaneous edits I did.

**Pull request closed without merging**
