### PR TITLE
Following compiler update, adhere more to Rust 2018 idioms

### PR DESCRIPTION
**Pull request by Luke-Nukem**
PR to update code to more Rust 2018 idioms.

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @Fraser999 (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by Luke-Nukem** [comment]
Local test runs were successful. Hopefully Travis is a good guy.

**Comment by pierrechevalier83** [comment]
Looks good to me @Luke-Nukem , thanks for contributing. Any particular reason the PR says "WIP"? Do you have upcoming commits you would like for us to wait on before merging?

**Comment by Luke-Nukem** [comment]
No reason other than that's what I called my branch I guess.
Everything is done as far as I can see. Removes a fair amount of "use" ambiguity.

**Comment by pierrechevalier83** [comment]
Thanks a lot :smile:

**Pull request merged**
