### PR TITLE
Network fullness check and project structure update..

### PR DESCRIPTION
**Pull request by brian-js**
Check network state at MaidManager and rework project structure.

On a Put request from a Client compare close group with full pmid nodes
returning failure if 50% or more close nodes are present.
Moved bin folder to src/bin in line with recommended directory structure. Use default safe_vault name for lib.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/412) &emsp; Multiple assignees:&emsp;@Fraser999&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/Fraser999">Fraser999</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/dirvine">dirvine</a>,&emsp;@maqi&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/maqi">maqi</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by brian-js** [comment]
+@dirvine +@maqi +@fraser999 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-:-KF4eJ14G4WiF0S3fKuc:-140158525)*

**Comment by Viv-Rajkumar** [comment]
*[src/personas/maid_manager.rs, line 808 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4etT9JFO9dRrCQmyz:-KF4etT9JFO9dRrCQmz-:-1612182729) ([raw file](https://github.com/maidsafe/safe_vault/blob/1567b37b56bd195d6111722d85365c4fee9bf726/src/personas/maid_manager.rs#L808)):*
instead of a `if let Ok(())` and `{}` with else being `unreachable()` isn't it better to just `assert!(env.maid_manager.handle_put(...).is_ok())`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by maqi** [comment]
*[src/personas/maid_manager.rs, line 205 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4gUIXOksn6zLrMeUd:-KF4gUIXOksn6zLrMeUe:981751043) ([raw file](https://github.com/maidsafe/safe_vault/blob/1567b37b56bd195d6111722d85365c4fee9bf726/src/personas/maid_manager.rs#L205)):*
this shall not happen, but once it happen, shall some log to be recorded and return?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by maqi** [comment]
*[a discussion](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4hVwTtiPmZI4OlBPd:-KF4hVwTtiPmZI4OlBPe:-1291488454) (no related file):*
The IDM will still sends back a NetworkFull put_failure back to CM.
shall that part be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by brian-js** [comment]
*[src/personas/maid_manager.rs, line 808 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4etT9JFO9dRrCQmyz:-KF4hJVWKZlZdYc_1FT0:116611299) ([raw file](https://github.com/maidsafe/safe_vault/blob/1567b37b56bd195d6111722d85365c4fee9bf726/src/personas/maid_manager.rs#L808)):*
I'd go with that, yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by brian-js** [comment]
*[a discussion](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4hVwTtiPmZI4OlBPd:-KF4jc-CKv606lUibOKV:-2096261827) (no related file):*
Ah, yes, missed that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by dirvine** [comment]
Reviewed 2 of 6 files at r2.
Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by brian-js** [comment]
*[src/personas/maid_manager.rs, line 205 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4gUIXOksn6zLrMeUd:-KF4qDPeHDFMSwUNCoAl:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/1567b37b56bd195d6111722d85365c4fee9bf726/src/personas/maid_manager.rs#L205)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by brian-js** [comment]
*[a discussion](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4hVwTtiPmZI4OlBPd:-KF4qH2Cx8-BLRRTN0ep:931454477) (no related file):*
Fixed and updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by brian-js** [comment]
*[src/personas/maid_manager.rs, line 808 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4etT9JFO9dRrCQmyz:-KF4qNy3ZuWZPoykVWZl:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/1567b37b56bd195d6111722d85365c4fee9bf726/src/personas/maid_manager.rs#L808)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by maqi** [comment]
*[src/personas/maid_manager.rs, line 786 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4s0kgmFmCq2qQNHMW:-KF4s0khw2qKwVpwIdYz:-843588896) ([raw file](https://github.com/maidsafe/safe_vault/blob/ae8edc88e495483d096409939b3454c8d725b920/src/personas/maid_manager.rs#L786)):*
better not to use the full list but only half of it, to prove we are working at 50%, not 100%

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by maqi** [comment]
*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by dirvine** [comment]
@brian-js  Seems like CI failures here can you please check.

---

Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-:-KF4x-YTMZOuRJjzSjAt:-715788561)*

**Comment by brian-js** [comment]
*[src/personas/maid_manager.rs, line 786 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-KF4s0kgmFmCq2qQNHMW:-KF4wovpqXYQ-TA2JHCf:-1497846108) ([raw file](https://github.com/maidsafe/safe_vault/blob/ae8edc88e495483d096409939b3454c8d725b920/src/personas/maid_manager.rs#L786)):*
Was mainly testing the error here, but point taken. Updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by maqi** [comment]
it might be because of the use of safe_core 0.14.1, but routing is still at 0.13.0

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-:-KF5117GBEpJpGZwrzJJ:1660469911)*

**Comment by dirvine** [comment]
Can we fix this first please. 

---

Review status: 2 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-:-KF51NLEQSnKUU8lDLmc:-1734385370)*

**Comment by brian-js** [comment]
@dirvine @maqi We need to update to the published crates. It's probably easier to merge Qi's PR first since it includes the refresh updates.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-:-KF51r3udaKK63v1-qRL:1413501270)*

**Comment by maqi** [comment]
yeah, using the new routing means the refresh updates, better have PR 413 merged first

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412#-:-KF550V300oN39bJvGDl:1073430165)*

**Comment by dirvine** [comment]
Reviewed 4 of 6 files at r2, 1 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Comment by maqi** [comment]
Reviewed 5 of 6 files at r2, 1 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/412)*

**Pull request merged**
