### PR TITLE
charge by unit

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/383) &emsp; Multiple assignees:&emsp;@Fraser999&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/Fraser999">Fraser999</a>,&emsp;@brian-js&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/brian-js">brian-js</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/dirvine">dirvine</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
+@dirvine +@brian-js 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-:-KDcTK3M1o4BVKPygyqE:-371172488)*

**Comment by Fraser999** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcUqc0RwjU3bVqR2Wy:-KDcUqc0RwjU3bVqR2Wz:-503876161) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L36)):*
Should we leave this as `u64`?  Also why the increase in account size?

---

*[src/personas/maid_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcVRbvrU8tp_GeudHk:-KDcVRbwSw0p96VQ5diC:-1786589688) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L37)):*
I guess I'd prefer this left as a `u64` too, or else just removed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcVRbvrU8tp_GeudHk:-KDcVvVOCSQ0b3g8NYj-:1886716016) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L37)):*
I think for now remove? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by maqi** [comment]
*[src/personas/maid_manager.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcUqc0RwjU3bVqR2Wy:-KDcVoXwNtsLImnD_gcq:-388654972) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L36)):*
SD will be limited to size 100KB, as now we starts charging by unit, so the account size shall be increased to reflect that. otherwise the allowance maybe too soon to be drained out.
regarding charging from u64 to u16, first is to reflect the real usage, second is the compiler can tell you where to change

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by maqi** [comment]
*[src/personas/maid_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcVRbvrU8tp_GeudHk:-KDcWZFYuVR6E5489guc:1250569858) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L37)):*
keep this just to ease the work of : if we want to change back to charge by data_size; no need to modify the testing code

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcUqc0RwjU3bVqR2Wy:-KDcWq5mNdy8zQdYgwaf:1210970463) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L36)):*
Yes although and  SD can only be 0.1 of a chunk (at most)  we always charge 1 unit to store, therefor it's all 1 unit if that makes sense. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcVRbvrU8tp_GeudHk:-KDcXACJBm_f8KwHUF5F:-1608101618) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L37)):*
For now though it's code we do not need. I would say and RFC will have to change this paradigm now as it was an rfc that created what we are doing. So the code change then is small. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by Fraser999** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcUqc0RwjU3bVqR2Wy:-KDcXelnpb_4BTcOxBdJ:20657156) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L36)):*
> first is to reflect the real usage
This limits the account to 65536 chunks.  Not sure that's a reasonable limit for the future.  I think we should stick with `u64` personally.

Also, we previously charged SDs at `DEFAULT_PAYMENT`, not their actual size, so you've doubled the account size from previously.

---

*[src/personas/maid_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcVRbvrU8tp_GeudHk:-KDcZ6amKquOb8FJNotr:-2066043960) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L37)):*
I agree with David here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by maqi** [comment]
*[src/personas/maid_manager.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcUqc0RwjU3bVqR2Wy:-KDcbQw_lEsnoA7Tu0qb:-1596720823) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L36)):*
u16 is fine or prefer still staying with u64?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by Fraser999** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcUqc0RwjU3bVqR2Wy:-KDccEGqE6isLDg-4QFm:-538672679) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L36)):*
I prefer `u64`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by maqi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/maid_manager.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcUqc0RwjU3bVqR2Wy:-KDceyrHIODCup9dE58I:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L36)):*
Done.

---

*[src/personas/maid_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/383#-KDcVRbvrU8tp_GeudHk:-KDcexgVzcy6Elw1ksXH:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/a9b3a182b89c5a5d5760dc940f43b7a6fa602dec/src/personas/maid_manager.rs#L37)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/383)*

**Pull request merged**
