### PR TITLE
feat/vault: configurable chunk_store root directory

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/500)

### CODE REVIEW

**Comment by afck** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[installer/common/sample.vault.config, line 4 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/500#-KKiGgiNLHAaBlOO6acG:-KKiGgiNLHAaBlOO6acH:1735599943) ([raw file](https://github.com/maidsafe/safe_vault/blob/b9d8255d2f5737d1517a63976592d608683551ab/installer/common/sample.vault.config#L4)):*
> ```
>   "wallet_address": null,
>   "max_capacity": 104857600,
>   "store_root": null
> ```

Not sure whether this will be easy to understand for users. Maybe `chunk_store_path`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/500)*

**Comment by maqi** [comment]
*[installer/common/sample.vault.config, line 4 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/500#-KKiGgiNLHAaBlOO6acG:-KKiQ82MKAG0lMBjZ6fK:796360058) ([raw file](https://github.com/maidsafe/safe_vault/blob/b9d8255d2f5737d1517a63976592d608683551ab/installer/common/sample.vault.config#L4)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Not sure whether this will be easy to understand for users. Maybe `chunk_store_path`?
</details>
committed by mistake, now resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/500)*

**Comment by afck** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vault.rs, line 53 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/500#-KKm7KNETgN5HXryFq3k:-KKm7KNF_HZo0P8EAH94:-454479672) ([raw file](https://github.com/maidsafe/safe_vault/blob/a0cfb648497bd2c07b12126bf3e62cbeda6d038f/src/vault.rs#L53)):*
> ```Rust
>         sodiumoxide::init();
> 
>         let config = config_handler::read_config_file().unwrap_or(Config::default());
> ```

Does `unwrap_or_else(Config::default)` work here, too? That wouldn't create a `Config` instance and immediately throw it away again in case there is a config file.

---

*[src/vault.rs, line 62 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/500#-KKm7oOLgibZXkSg0_Xj:-KKm7oOLgibZXkSg0_Xk:-1758555099) ([raw file](https://github.com/maidsafe/safe_vault/blob/a0cfb648497bd2c07b12126bf3e62cbeda6d038f/src/vault.rs#L62)):*
> ```Rust
>                 root_path.to_path_buf()
>             } else {
>                 env::temp_dir()
> ```

Should we print a warning here? Like `{:?} is not a directory`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/500)*

**Comment by afck** [comment]
Reviewed 3 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/500)*

**Comment by maqi** [comment]
*[src/vault.rs, line 53 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/500#-KKm7KNETgN5HXryFq3k:-KKmAJ1IoTWgahXUcSIs:1262173026) ([raw file](https://github.com/maidsafe/safe_vault/blob/a0cfb648497bd2c07b12126bf3e62cbeda6d038f/src/vault.rs#L53)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Does `unwrap_or_else(Config::default)` work here, too? That wouldn't create a `Config` instance and immediately throw it away again in case there is a config file.
</details>
neither `unwrap_or_else(Config::default())` nor `unwrap_or_else(Config::default)` passes compilation  :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/500)*

**Comment by maqi** [comment]
*[src/vault.rs, line 62 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/500#-KKm7oOLgibZXkSg0_Xj:-KKmAf6u07Eht7jrrBvi:677588487) ([raw file](https://github.com/maidsafe/safe_vault/blob/a0cfb648497bd2c07b12126bf3e62cbeda6d038f/src/vault.rs#L62)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Should we print a warning here? Like `{:?} is not a directory`?
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/500)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/500)*

**Pull request merged**
