### PR TITLE
updated crust to 0.5.0 and fixed some changes in std

### PR DESCRIPTION
**Pull request by waynenilsen**
see also #309 @maqi

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @Fraser999 (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by rossmuir** [comment]
@waynenilsen sorry there seems to be some crossed wires I have duplicated a lot of your PR and even stolen your fixes :-( - sorry. I got the link in slack, but didn't notice it was a PR to `safe_vault` my bad and grabbed the fixes - I will credit you in the final PR. Apologies for the rudeness.

**Comment by dirvine** [comment]
How wude - in the voice of Jar Jar Binks :8ball:

**Comment by waynenilsen** [comment]
@dirvine :laughing: I don't mind, just excited to see the vault build back to green on travis

**Pull request closed without merging**
