### PR TITLE
test/mock_crust_churn_test: verify kademlia invariant for all nodes

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/499)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
I guess we'll have to wait for the next routing version change for this to compile. But we'll do one this week. :thumbsup: 

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/mock_crust_detail/mod.rs, line 89 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/499#-KKgcQikrpsUA2eWfJ3q:-KKgcQily4_095Ll_8JZ:266066388) ([raw file](https://github.com/maidsafe/safe_vault/blob/8584fbe408bd2dbca383d277855e180b8c211e9f/src/mock_crust_detail/mod.rs#L89)):*
> ```Rust
> /// Verify that the kademlia invariant is upheld for all nodes.
> pub fn verify_kademlia_invariant_for_all_nodes(nodes: &[TestNode]) {
>     let routing_tables = nodes.iter().map(|node| node.routing_table()).collect();
> ```

Does `map(TestNode::routing_table)` work here, too? Then there's no need for this closure.

---

*[src/mock_crust_detail/test_node.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/499#-KKgbkNSf00dfxAcJt0_:-KKgbkNTju6MaDBzSbRf:-2068852750) ([raw file](https://github.com/maidsafe/safe_vault/blob/8584fbe408bd2dbca383d277855e180b8c211e9f/src/mock_crust_detail/test_node.rs#L87)):*
> ```Rust
>         self.vault.name()
>     }
>     /// routing_table of vault.
> ```

Let's stick to the recommended format for comments (see https://github.com/rust-lang/rust/blob/master/src/doc/style/style/comments.md); maybe: "Returns the vault's routing table."

Clippy would probably complain about this line, too. Please make sure to not introduce new Clippy errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/499#-:-KKgckyBNLIV-h1LvVEA:196188359)*

**Comment by maqi** [comment]
*[src/mock_crust_detail/mod.rs, line 89 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/499#-KKgcQikrpsUA2eWfJ3q:-KKmCK7hUgIk6fEi9TAB:-1407218161) ([raw file](https://github.com/maidsafe/safe_vault/blob/8584fbe408bd2dbca383d277855e180b8c211e9f/src/mock_crust_detail/mod.rs#L89)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Does `map(TestNode::routing_table)` work here, too? Then there's no need for this closure.
</details>
changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/499)*

**Comment by maqi** [comment]
*[src/mock_crust_detail/test_node.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/499#-KKgbkNSf00dfxAcJt0_:-KKmCOYN4I1cWkBh-MyZ:-1407218161) ([raw file](https://github.com/maidsafe/safe_vault/blob/8584fbe408bd2dbca383d277855e180b8c211e9f/src/mock_crust_detail/test_node.rs#L87)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Let's stick to the recommended format for comments (see https://github.com/rust-lang/rust/blob/master/src/doc/style/style/comments.md); maybe: "Returns the vault's routing table."
> 
> Clippy would probably complain about this line, too. Please make sure to not introduce new Clippy errors.
</details>
changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/499)*

**Comment by afck** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/499)*

**Comment by afck** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/499)*

**Pull request merged**
