### PR TITLE
Implement handlers for read-only operations on append-only data

### LINKED ISSUE #703: Handle GetAData, GetADataShell, GetADataRange, GetADataIndices, GetADataLastEntry, GetADataPermissions, GetADataOwners, GetPubADataUserPermissions and GetUnpubADataUserPermissions

### PR DESCRIPTION
**Pull request by madadam**
- [x] GetAData
- [x] GetADataShell
- [x] GetADataRange
- [x] GetADataIndices
- [x] GetADataLastEntry
- [x] GetADataPermissions
- [x] GetADataOwners
- [x] GetPubADataUserPermissions 
- [x] GetUnpubADataUserPermissions
- [x] GetAdataValue
- [x] tests for all the above

Closes #703

### CODE REVIEW

**Comment by octol** [comment]
Playing around with GetAData I'm observing this
```
common::perform_mutation(&mut env, &mut client_a, Request::PutAData(AData::PubSeq(data.clone())));
common::send_request_expect_response(
    &mut env,
    &mut client_b,
    Request::GetAData(*data.address()),
    Response::GetAData(Err(NdError::NoSuchEntry)),
);
```
when I probably would have expected `NdError::AccessDenied`?

**Comment by octol** [comment]
BTW I'm not seeing any tests for Unseq data? (Maybe it's not necessary?)

**Comment by madadam** [comment]
> BTW I'm not seeing any tests for Unseq data? (Maybe it's not necessary?)

Don't think they are necessary. With only the read-only operations that this PR implements, there is no difference between seq and unseq.

**Comment by octol** [comment]
Updated my PR ontop of this and the new permission handling and I spotted this
```
    // Only client A has permissions to add permissions
    common::send_request_expect_response(
        &mut env,
        &mut client_b,
        Request::AddPubADataPermissions {
            address: *data.address(),
            permissions: perms_1.clone(),
            permissions_idx: 1,
        },
        // TODO: this should probably be AccessDenied?
        Response::Mutation(Err(NdError::InvalidPermissions)),
    );

    common::perform_mutation(
        &mut env,
        &mut client_a,
        Request::AddPubADataPermissions {
            address: *data.address(),
            permissions: perms_1.clone(),
            permissions_idx: 1,
        },
    );
```

Only client A has permissions

**Pull request merged**
