### PR TITLE
chore/deps: migrate to rust_sodium and routing 0.23.4

### PR DESCRIPTION
**Pull request by afck**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/541)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 16 files at r3, 15 of 15 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/541)*

**Pull request merged**
