### PR TITLE
safe_vault/tests update

### PR DESCRIPTION
**Pull request by brian-js**
Split code into a vault library and safe_vault binary, and use integration test structure for mock-crust tests.

Created a vault library and a safe_vault binary linking to the library. Moved the mock-crust tests from src/tests to tests folder and updated code to use exported vault library details. Removes unrequired/commented tests/code from codebase.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/410) &emsp; Multiple assignees:&emsp;@Fraser999&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/Fraser999">Fraser999</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/dirvine">dirvine</a>,&emsp;@maqi&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/maqi">maqi</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by brian-js** [comment]
+@dirvine +@fraser999 +@maqi

**Comment by brian-js** [comment]
+@dirvine +@fraser999 +@maqi

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/410#-:-KEqCuq-Sp-GfrvzXBML:-991719125)*

**Comment by maqi** [comment]
*[a discussion](https://reviewable.io:443/reviews/maidsafe/safe_vault/410#-KEwFKB7fFGj0StZEVOh:-KEwFKB7fFGj0StZEVOi:-2129651426) (no related file):*
shall the compilation of safe_vault binary being checked by the CI?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/410)*

**Comment by maqi** [comment]
*[bin/safe_vault.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/410#-KEwFYtsXX7YzkeIw8i_:-KEwFYtt9XpB5K-pAgwb:660986231) ([raw file](https://github.com/maidsafe/safe_vault/blob/a590ea1b5311a1cd25374c8e1ea99b41a73493b4/bin/safe_vault.rs#L52)):*
this `unused_extern_crates` is for what?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/410)*

**Comment by maqi** [comment]
*[src/lib.rs, line 1 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/410#-KF0PUQKdKTI_pQTw4TI:-KF0PUQKdKTI_pQTw4TJ:676036456) ([raw file](https://github.com/maidsafe/safe_vault/blob/a590ea1b5311a1cd25374c8e1ea99b41a73493b4/src/lib.rs#L1)):*
2016

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/410)*

**Comment by brian-js** [comment]
*[a discussion](https://reviewable.io:443/reviews/maidsafe/safe_vault/410#-KEwFKB7fFGj0StZEVOh:-KF3UhdqnUNE37IShpqm:-1339679843) (no related file):*
It's built when the tests are compiled. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/410)*

**Comment by brian-js** [comment]
*[bin/safe_vault.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/410#-KEwFYtsXX7YzkeIw8i_:-KF3W25MFLU3I77GXeN1:1694143334) ([raw file](https://github.com/maidsafe/safe_vault/blob/a590ea1b5311a1cd25374c8e1ea99b41a73493b4/bin/safe_vault.rs#L52)):*
When compiling with mock-crust feature nothing is used and other options were a bit messy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/410)*

**Comment by brian-js** [comment]
*[src/lib.rs, line 1 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/410#-KF0PUQKdKTI_pQTw4TI:-KF3WubDzELy2lU0znGk:1092443852) ([raw file](https://github.com/maidsafe/safe_vault/blob/a590ea1b5311a1cd25374c8e1ea99b41a73493b4/src/lib.rs#L1)):*
Of course it is. I'll push a fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/410)*

**Comment by maqi** [comment]
Reviewed 11 of 17 files at r1, 3 of 5 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/410)*

**Pull request merged**
