### PR TITLE
SDM unit tests

### PR DESCRIPTION
**Pull request by maqi**
Affects only structured_data_manager.rs

unit tests for SDM
getter of stored chunk list for CI_test

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/396) &emsp; Multiple assignees:&emsp;@Fraser999&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/Fraser999">Fraser999</a>,&emsp;@brian-js&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/brian-js">brian-js</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/dirvine">dirvine</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
+@dirvine +@brian-js +@fraser999 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/396#-:-KE7paq9QmASfys3QLn3:752104063)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/structured_data_manager.rs, line 243 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/396#-KE7qmd3r9s7sbk1GGsg:-KE7qmd3r9s7sbk1GGsh:-759613983) ([raw file](https://github.com/maidsafe/safe_vault/blob/29b482c560c1d2b8f252e24ff6d29eadb2386a57/src/personas/structured_data_manager.rs#L243)):*
Actually sorry @maqi  On seeing this I feel the function should be called `get_stored_names()` not chunk names and then it's consistent. @brian-js  can you also use this name. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/396)*

**Comment by maqi** [comment]
*[src/personas/structured_data_manager.rs, line 243 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/396#-KE7qmd3r9s7sbk1GGsg:-KE7tzg9xy42GFNcuiEm:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/29b482c560c1d2b8f252e24ff6d29eadb2386a57/src/personas/structured_data_manager.rs#L243)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/396)*

**Comment by brian-js** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/396)*

**Comment by brian-js** [comment]
*[src/personas/structured_data_manager.rs, line 245 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/396#-KE8SG3h_55hVIBj6WD9:-KE8SG3h_55hVIBj6WDA:628319983) ([raw file](https://github.com/maidsafe/safe_vault/blob/29b482c560c1d2b8f252e24ff6d29eadb2386a57/src/personas/structured_data_manager.rs#L245)):*
Should be get_stored_names as David suggested.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/396)*

**Comment by brian-js** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/396)*

**Comment by Fraser999** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/396)*

**Pull request merged**
