### PR TITLE
Cleanup work.

### PR DESCRIPTION
**Pull request by Fraser999**
Affects mainly personas holding ChunkStores (MpidMgr, PN, SDM).

This simplifies the handling of capacity calculations for ChunkStores.  The default total capacity and personas' ratios are defined as consts in vault.rs now.
The default_chunk_store was no longer needed and hence removed.
Unwraps were removed from the constructors of MpidManager and StructuredDataManager.
Updated dependencies.
Ran rustfmt.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/392) &emsp; Multiple assignees:&emsp;@brian-js&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/brian-js">brian-js</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/dirvine">dirvine</a>,&emsp;@maqi&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/maqi">maqi</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Fraser999** [comment]
+@dirvine +@brian-js

**Comment by Fraser999** [comment]
+@dirvine +@brian-js +@maqi

**Comment by Fraser999** [comment]
+@dirvine +@brian-js +@maqi

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/392#-:-KE0yDqExZFEeWoOFp5u:-235590887)*

**Comment by maqi** [comment]
*[src/personas/mpid_manager.rs, line 721 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/392#-KE0yrlttmkqFwQrv1FN:-KE0yrlumWJKobfb3445:1814753821) ([raw file](https://github.com/maidsafe/safe_vault/blob/d4809e9a71516304a35530a08a83c600b43ac879/src/personas/mpid_manager.rs#L721)):*
can we use DEFAULT_MAX_CAPACITY * MPID_MANAGER_ALLOWANCE  here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/392)*

**Comment by Fraser999** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/mpid_manager.rs, line 721 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/392#-KE0yrlttmkqFwQrv1FN:-KE0znlFWKWfbIKxImIh:-99151778) ([raw file](https://github.com/maidsafe/safe_vault/blob/d4809e9a71516304a35530a08a83c600b43ac879/src/personas/mpid_manager.rs#L721)):*
Not without making these `pub` in vault.rs which I'd prefer to not do just to accommodate unit tests.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/392)*

**Comment by brian-js** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/392)*

**Comment by maqi** [comment]
Reviewed 14 of 14 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/392)*

**Comment by maqi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/392)*

**Pull request merged**
