### PR TITLE
Delete churn test; DM deletion cache

### PR DESCRIPTION
**Pull request by maqi**
Affects: Cargo.toml src/lib.rs src/personas/data_manager.rs tests/mock_crust.rs

Having a deletion cache in DM to reject improper refresh in data.
Enable the delete test in structured_data_churn

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/429)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFstly9sx3X5RUkc6Ln:-KFstly9sx3X5RUkc6Lo:256329428) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L44)):*
Feels a bit dirty (although should work & maybe only way for now) , but in any case I think this time needs to be related to max_capacity of the data we store in vaults and how long we allow for churn to take place. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/data_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFsuJnCt17sXYbJMsuA:-KFsuJnCt17sXYbJMsuB:398638455) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L37)):*
What is the `u64` for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/data_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFsuJnCt17sXYbJMsuA:-KFsuSogQxG7aRHZORx9:491145708) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L37)):*
Perhaps this should be a message_filter ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFsuJnCt17sXYbJMsuA:-KFswaLoh0jjRx6AgKvS:753842540) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L37)):*
this u64 is for version.
However, it is not mandatory to put version in. It is used here just because seems LruCache can't be used as taking key only.
message_filter doesn't provide a `remove` function, otherwise it is more suitable. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Comment by maqi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/data_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFsuJnCt17sXYbJMsuA:-KFswaLoh0jjRx6AgKvS:753842540) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L37)):*
this u64 is for version.
However, it is not mandatory to put version in. It is used here just because seems LruCache can't be used as taking key only.
message_filter doesn't provide a `remove` function, otherwise it is more suitable. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFstly9sx3X5RUkc6Ln:-KFsxxQLeLNKFgakdGMZ:696382348) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L44)):*
yeah, I agree. but will that be hard to `limit` the churn interval in real network deployment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/data_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFsuJnCt17sXYbJMsuA:-KFsy7D154vbJIvemo2x:1596672219) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L37)):*
Perhaps think of PR to message_filter ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFsuJnCt17sXYbJMsuA:-KFsyFaX4atDPCMPB-sV:-570542055) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L37)):*
not sure if it worth it to update the lib. I will raise a PR anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/personas/data_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFsuJnCt17sXYbJMsuA:-KFt2W3swh8XHWvH7jbz:-1482455937) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L37)):*
Yes, I doubt this PR will make Alpha-1 release so we will have time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/429#-KFsuJnCt17sXYbJMsuA:-KFt4BkzsL2eov6wpPeN:1987788282) ([raw file](https://github.com/maidsafe/safe_vault/blob/eef359bdf373b88ff56d9462702ad121e38856c2/src/personas/data_manager.rs#L37)):*
lucky, you are reviewer for the message_filter PR   :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/429)*

**Pull request closed without merging**
