### PR TITLE
Remove lints that are unavailable in rustc 1.31

### PR DESCRIPTION
**Pull request by octol**

### CODE REVIEW

**Comment by octol** [comment]
Removed the outdated links

**Comment by m-cat** [comment]
> Removed the outdated links

We should keep this part, as it still works fine and shows a list of what all the lint checks do.

```
// For explanation of lint checks, run `rustc -W help`.
```

**Comment by octol** [comment]
> > Removed the outdated links
> 
> We should keep this part, as it still works fine and shows a list of what all the lint checks do.
> 
> ```
> // For explanation of lint checks, run `rustc -W help`.
> ```

Updated!

**Comment by octol** [comment]
Sorry I noticed I missed to remove two lints in the tests, so updated again

**Comment by Luke-Nukem** [comment]
Created new PR # 672

**Pull request closed without merging**
