### PR TITLE
updating libs, allowing some lints

### PR DESCRIPTION
**Pull request by waynenilsen**
the changes to `Cargo.toml` should be rolled back but for now they were needed to compile, also should do a minor version bump

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/309)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @maqi (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by maqi** [comment]
Hi, there,

Thanks for the contribution.
As you can see, the PR failed CI builds when trying building tests using mock routing (cargo test --features "use-mock-routing")

Also, there is a policy that "allow" shall be avoided. Is it possible to remove the un-used parts?

One last thing is regarding the routing version to be used. Pointing to a specific commit shall be avoided, so seems we have to wait for the version pump of routing lib to be completed.

**Comment by maqi** [comment]
Hi, there,

I cross checked with other stuff and seems the lint changes are due to the same issue as reported in https://github.com/maidsafe/crust/issues/410, which should be fixed in the next release of Rust nightly hopefully.

Regarding the dependency image, it is preferred not to include the svg file directly, instead of having some post-commit auto-generating hook to anyone else can view it online if interested.

So, I will close this PR at this moment.

**Comment by waynenilsen** [comment]
I think that removing  the deprecated `sleep_ms` and upgrading the crust version should probably be included, do you? I can roll back the other changes.

**Comment by dirvine** [comment]
:+1:

**Comment by maqi** [comment]
Hi, Waynenilsen,

Could you please raise a new PR only includes the part removing deprecated `sleep_ms` and updating crust version?
thx.

**Pull request closed without merging**
