### PR TITLE
test/data_manager: migrate previous mock_routing tests

### PR DESCRIPTION
**Pull request by maqi**
Refactor some of previous mock_routing tests to using mock_crust

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/463)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mock_crust_detail/test_client.rs, line 138 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/463#-KGwjhzwNIeFs5ULZGR0:-KGwjhzwNIeFs5ULZGR1:-1929422001) ([raw file](https://github.com/maidsafe/safe_vault/blob/2c0cb2c41f78f03cf1642d754d8937d5c9ce755f/src/mock_crust_detail/test_client.rs#L138)):*
I Think this will return the count of events which may be very useful in these tests ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/463)*

**Comment by afck** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/mock_crust_detail/test_client.rs, line 127 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/463#-KGwnXBqBAW_GJ4kOd12:-KGwnXBrcRwe5J7hZ2z5:-1193727248) ([raw file](https://github.com/maidsafe/safe_vault/blob/2c0cb2c41f78f03cf1642d754d8937d5c9ce755f/src/mock_crust_detail/test_client.rs#L127)):*
Maybe `Sends a Get request, polls the mock network and expects a Get response.` would be clearer? (Similarly for the other request types.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/463)*

**Comment by maqi** [comment]
*[src/mock_crust_detail/test_client.rs, line 138 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/463#-KGwjhzwNIeFs5ULZGR0:-KH-BQWOiXNg2dODep20:-1890517911) ([raw file](https://github.com/maidsafe/safe_vault/blob/2c0cb2c41f78f03cf1642d754d8937d5c9ce755f/src/mock_crust_detail/test_client.rs#L138)):*
the returned event count is not consistent across iterations.
for example, for test handle_delete_error_flow, in one iteration,
the returned event counts are: 30, 25, 30, 30, 30
however in another iteration : 25, 25, 25, 25, 25
although it is interested to know, but I'm afraid we can't put in any assertion here. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/463)*

**Comment by afck** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/mock_crust_detail/test_client.rs, line 138 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/463#-KGwjhzwNIeFs5ULZGR0:-KH-DGOufhh5IHdQ0gtk:485447457) ([raw file](https://github.com/maidsafe/safe_vault/blob/2c0cb2c41f78f03cf1642d754d8937d5c9ce755f/src/mock_crust_detail/test_client.rs#L138)):*
It's not expected to be consistent currently, as it depends on the distribution of node names and our tests are (unfortunately) not deterministic.
But it might be interesting to put these in as `trace!` messages so that when we want to analyse efficiency later, we only need to add a `log::init` to see the count.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/463)*

**Comment by afck** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/personas/data_manager.rs, line 602 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/463#-KH-vddvSxLGgidj3Pwb:-KH-vddwIQ-XBeiFOGNz:482064997) ([raw file](https://github.com/maidsafe/safe_vault/blob/e831a6d867c9d847b9699c80571f93aaf6c96e30/src/personas/data_manager.rs#L602)):*
I think that might cause a lot of spam in a large vault on `NodeAdded`, since we're calling this in a loop there.
Also, are there any places left where we change a `_data_count` without calling one of these two methods?

---

*[tests/data_manager.rs, line 358 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/463#-KH-vRe2S6kjmo3P4eqe:-KH-vRe2S6kjmo3P4eqf:-408807529) ([raw file](https://github.com/maidsafe/safe_vault/blob/e831a6d867c9d847b9699c80571f93aaf6c96e30/tests/data_manager.rs#L358)):*
I'd remove the `_without_churn`. I think it's enough if the tests that _do_ simulate churn have `_with_churn`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/463)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 602 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/463#-KH-vddvSxLGgidj3Pwb:-KH-wK2KNoLYHD1W17un:-1143970943) ([raw file](https://github.com/maidsafe/safe_vault/blob/e831a6d867c9d847b9699c80571f93aaf6c96e30/src/personas/data_manager.rs#L602)):*
there is one place in node_lost changing immutable_data_count without calling this method.
regarding the spam of printing msg, yeah, it will be an issue. i may need to revert it then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/463)*

**Comment by afck** [comment]
Reviewed 3 of 7 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/463)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/463)*

**Pull request merged**
