### PR TITLE
Unit tests for PmidNode.

### PR DESCRIPTION
**Pull request by brian-js**
Unit tests for PmidNode

Tests the PmidNode persona functionality.

Added various scenario tests to PmidNode.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/397) &emsp; Multiple assignees:&emsp;@Fraser999&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/Fraser999">Fraser999</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/dirvine">dirvine</a>,&emsp;@maqi&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/maqi">maqi</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by brian-js** [comment]
+@dirvine +@maqi +@fraser999 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/397#-:-KE8Pcqw1mMpqYe7haYI:-140158525)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/pmid_node.rs, line 166 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/397#-KEC9y0vCeyX9EXqfl4y:-KEC9y0vCeyX9EXqfl4z:-41222183) ([raw file](https://github.com/maidsafe/safe_vault/blob/e28a845a503789da7d312e0acdb448297a98f60f/src/personas/pmid_node.rs#L166)):*
IS this making all following tests not run when this feature is not set? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/397)*

**Comment by maqi** [comment]
*[src/personas/pmid_node.rs, line 166 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/397#-KEC9y0vCeyX9EXqfl4y:-KECAD72IKbZNSegK-6L:-1936282623) ([raw file](https://github.com/maidsafe/safe_vault/blob/e28a845a503789da7d312e0acdb448297a98f60f/src/personas/pmid_node.rs#L166)):*
i think yes. most persona function having a routing object to be passed down.
so `use-mock-routing` seems always required

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/397)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/pmid_node.rs, line 166 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/397#-KEC9y0vCeyX9EXqfl4y:-KECBQiAabp2TGuPPke_:1915599183) ([raw file](https://github.com/maidsafe/safe_vault/blob/e28a845a503789da7d312e0acdb448297a98f60f/src/personas/pmid_node.rs#L166)):*
So this leaves no stand alone unit tests at all here? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/397)*

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/pmid_node.rs, line 166 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/397#-KEC9y0vCeyX9EXqfl4y:-KECBfPVh08RHZsNuSa5:1209763367) ([raw file](https://github.com/maidsafe/safe_vault/blob/e28a845a503789da7d312e0acdb448297a98f60f/src/personas/pmid_node.rs#L166)):*
I wonder if this is correct, seems these tests should be  able to run with real routing as well as mocks. this would mean they only run with mock, like all of them. So it seems a bit suicidal ;-)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/397)*

**Comment by maqi** [comment]
*[src/personas/pmid_node.rs, line 166 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/397#-KEC9y0vCeyX9EXqfl4y:-KECCQXd4TcMW201kq5I:2056212246) ([raw file](https://github.com/maidsafe/safe_vault/blob/e28a845a503789da7d312e0acdb448297a98f60f/src/personas/pmid_node.rs#L166)):*
using real routing means it will be difficult to capture the sent out request/response to verify whether the internal logic is correct or not, i.e. testing in black_box mode.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/397)*

**Comment by Fraser999** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/397)*

**Comment by maqi** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/397)*

**Pull request merged**
