### PR TITLE
refactor/ci: change clippy and rustc versions

### PR DESCRIPTION
**Pull request by ustulation**
Change clippy and rustc version in .travis.yml
Refactor to solve clippy errors

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by michaelsproul** [comment]
I think I fixed the remaining clippy errors in https://github.com/maidsafe/safe_vault/pull/606/commits/f1e46985b823913b335dd4404db147f01d8876a5, which I wrote when rebasing my SHA-3 PR on top of this PR https://github.com/maidsafe/safe_vault/pull/606

**Comment by ustulation** [comment]
Ah there are no more errors here after i pushed like 9 hrs back - i think it is erroring out due to some travis issue ?

**Comment by ustulation** [comment]
Merged in https://github.com/maidsafe/safe_vault/pull/606

**Pull request closed without merging**
