### PR TITLE
feat/chunk_store: create a lock file in the chunk directory

### PR DESCRIPTION
**Pull request by afck**
Only create the `ChunkStore` if a lock can be acquired on the chunk
directory.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/529)

### CODE REVIEW

**Comment by maqi** [comment]
*[src/chunk_store/chunk_store.rs, line 104 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/529#-KLansaK7GHSczk-ckun:-KLansaK7GHSczk-ckuo:1671682344) ([raw file](https://github.com/maidsafe/safe_vault/blob/fab8553848bb854b64dadfce3df512457326ad2b/src/chunk_store/chunk_store.rs#L104)):*
> ```Rust
>             }
>         }
> ```

is that if the function is less than 100 lines, we prefer not to split it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/529)*

**Comment by afck** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chunk_store/chunk_store.rs, line 104 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/529#-KLansaK7GHSczk-ckun:-KLaowyZZTA-ZobhGVFg:-1422811383) ([raw file](https://github.com/maidsafe/safe_vault/blob/fab8553848bb854b64dadfce3df512457326ad2b/src/chunk_store/chunk_store.rs#L104)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> is that if the function is less than 100 lines, we prefer not to split it?
</details>
No, I'm happy to split it up, if you prefer!
I just omitted the removal of the test file, since we're clearing the directory anyway. And without removing that, I thought, the separate method doesn't make much sense in itself anymore.

So I'm not sure which parts best to extract into methods: The directory and lock file creation? The test file creation and clearing of the directory together? Or all of them together?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/529)*

**Comment by dirvine** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chunk_store/chunk_store.rs, line 104 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/529#-KLansaK7GHSczk-ckun:-KLaqHKYwowHFwiJYzy-:1639383330) ([raw file](https://github.com/maidsafe/safe_vault/blob/fab8553848bb854b64dadfce3df512457326ad2b/src/chunk_store/chunk_store.rs#L104)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> No, I'm happy to split it up, if you prefer!
> I just omitted the removal of the test file, since we're clearing the directory anyway. And without removing that, I thought, the separate method doesn't make much sense in itself anymore.
> 
> So I'm not sure which parts best to extract into methods: The directory and lock file creation? The test file creation and clearing of the directory together? Or all of them together?
</details>
I would say only extract what would be used elsewhere really or if there is a specific functionality we can extricate that is sensible and more than a couple of lines in length, otherwise it's just indirection. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/529)*

**Comment by maqi** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/529)*

**Comment by afck** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chunk_store/chunk_store.rs, line 104 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/529#-KLansaK7GHSczk-ckun:-KLaryH_eP2QpNF0G9xN:-1861306587) ([raw file](https://github.com/maidsafe/safe_vault/blob/fab8553848bb854b64dadfce3df512457326ad2b/src/chunk_store/chunk_store.rs#L104)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> I would say only extract what would be used elsewhere really or if there is a specific functionality we can extricate that is sensible and more than a couple of lines in length, otherwise it's just indirection. 
</details>
Just to try it out: Here's a version with the whole root dir logic extracted. Not sure which one is nicer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/529)*

**Comment by dirvine** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chunk_store/chunk_store.rs, line 104 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/529#-KLansaK7GHSczk-ckun:-KLasJtXoF49XFYNoUsh:85366598) ([raw file](https://github.com/maidsafe/safe_vault/blob/fab8553848bb854b64dadfce3df512457326ad2b/src/chunk_store/chunk_store.rs#L104)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Just to try it out: Here's a version with the whole root dir logic extracted. Not sure which one is nicer?
</details>
It's' tase at this stage I think, either is probably good. Short descriptive single input single output is good though :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/529)*

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/529)*

**Pull request merged**
