### PR TITLE
MAID-1333: Initial run of RustFmt.  Added RustFmt configuration file.

### PR DESCRIPTION
**Pull request by Fraser999**

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
looks good to me

**Comment by benjaminbollen** [comment]
I've not given an indepth review, but rather scanned for "visible" difference, and all looked to be re-formatting as performed by Rustfmt

**Pull request merged**
