### PR TITLE
test/data_manager: appendable data churn test

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/550)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/data_manager.rs, line 435 at r1](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRgxeMc8hg100MWjuhp:-KRgxeMc8hg100MWjuhq:b2z9vn7) ([raw file](https://github.com/maidsafe/safe_vault/blob/ac13df6bc62441c744336824100e52a448215435/tests/data_manager.rs#L435)):*
> ```Rust
> 
> #[test]
> fn appendable_data_operations_with_churn_with_cache() {
> ```

We don't cache appendable data, so we don't need two separate tests here.

---

*[tests/data_manager.rs, line 467 at r1](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRgxuaTCxxPZYynGvGD:-KRgxuaTCxxPZYynGvGE:be86jze) ([raw file](https://github.com/maidsafe/safe_vault/blob/ac13df6bc62441c744336824100e52a448215435/tests/data_manager.rs#L467)):*
> ```Rust
>         let appended_data = unwrap_result!(AppendedData::new(pointer, pub_key, &secret_key));
>         let wrapper = AppendWrapper::new_pub(*data.name(), appended_data.clone(), 0);
>         let _ = client.append_and_verify(wrapper, &mut nodes);
> ```

This should only `append`. `append_and_verify` does all the polling and so it doesn't simulate the appending being handled at the same time as the churn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/550)*

**Comment by maqi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/data_manager.rs, line 435 at r1](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRgxeMc8hg100MWjuhp:-KRh34Fn3-FLg3lCp-up:b-w86br2) ([raw file](https://github.com/maidsafe/safe_vault/blob/ac13df6bc62441c744336824100e52a448215435/tests/data_manager.rs#L435)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> We don't cache appendable data, so we don't need two separate tests here.
</details>
the use_cache flag is for the node constructor API.
We are also not supposed to cache structured_data but the test also covers the `caching` flag.
I thought we shall follow the same pattern (prevents any mis-use of that caching capability?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/550)*

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/data_manager.rs, line 435 at r1](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRgxeMc8hg100MWjuhp:-KRh4elKyewWkgSxmUMJ:bc3blmw) ([raw file](https://github.com/maidsafe/safe_vault/blob/ac13df6bc62441c744336824100e52a448215435/tests/data_manager.rs#L435)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> the use_cache flag is for the node constructor API.
> We are also not supposed to cache structured_data but the test also covers the `caching` flag.
> I thought we shall follow the same pattern (prevents any mis-use of that caching capability?)
</details>
But instead of duplicating all those heavy churn tests, shouldn't we just add a single test then that make sure that data types other than immutable are never cached?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/550)*

**Comment by maqi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/data_manager.rs, line 435 at r1](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRgxeMc8hg100MWjuhp:-KRhXq8yy7KQ1ZVNplxE:bwkwll6) ([raw file](https://github.com/maidsafe/safe_vault/blob/ac13df6bc62441c744336824100e52a448215435/tests/data_manager.rs#L435)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> But instead of duplicating all those heavy churn tests, shouldn't we just add a single test then that make sure that data types other than immutable are never cached?
</details>
shall i remove the cache test for structured_data as well?
I think a get of new version of AD or SD is somehow verifies not cached, so maybe we don't need additional tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/550)*

**Comment by afck** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/data_manager.rs, line 435 at r1](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRgxeMc8hg100MWjuhp:-KRhixd2G3B9rUK8p5et:b-vvh637) ([raw file](https://github.com/maidsafe/safe_vault/blob/ac13df6bc62441c744336824100e52a448215435/tests/data_manager.rs#L435)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> shall i remove the cache test for structured_data as well?
> I think a get of new version of AD or SD is somehow verifies not cached, so maybe we don't need additional tests.
</details>
I agree, that's the very reason why we don't cache them. :+1: 
So maybe let's only have the versions with cache turned _on_, so that the tests verify that it isn't actually used.

---

*[tests/data_manager.rs, line 169 at r2](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRhjhnFagT1JFGtZ96q:-KRhjhnFagT1JFGtZ96r:bj58by7) ([raw file](https://github.com/maidsafe/safe_vault/blob/748ebcd1434f94e756496b384198e93dc5d72a72/tests/data_manager.rs#L169)):*
> ```Rust
>             .collect();
> 
>         event_count += poll::poll_and_resend_unacknowledged_parallel(&mut nodes, &mut clients);
> ```

Ah, yes! Thanks for deduplicating that! :+1: 

---

*[tests/data_manager.rs, line 518 at r2](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRhk9vfoy7RXoOkyHxW:-KRhk9vfoy7RXoOkyHxX:b-1b0d03) ([raw file](https://github.com/maidsafe/safe_vault/blob/748ebcd1434f94e756496b384198e93dc5d72a72/tests/data_manager.rs#L518)):*
> ```Rust
>                         trace!("Client {:?} received AppendSuccess.", client.name());
>                         ad.append(data);
>                         successes += 1;   
> ```

Is that a trailing whitespace? Please rerun rustfmt, it should remove that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/550)*

**Comment by afck** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/test_utils.rs, line 58 at r3](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRiW5lz7pi0qgurmREE:-KRiW5m-uBqkRviKmq_Q:bqm869u) ([raw file](https://github.com/maidsafe/safe_vault/blob/ce5fd488d13e36da4ed695a9bda8ef0427136f72/src/test_utils.rs#L58)):*
> ```Rust
> }
> 
> /// Creates random public appendable data - tests only
> ```

Should probably be updated to: `Creates a new public appendable data with an incremented version number`?

---

*[tests/data_manager.rs, line 564 at r3](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRiWs8TN6iokXjjBB_p:-KRiWs8UCKp5nlpEkDu8:b-9kff4p) ([raw file](https://github.com/maidsafe/safe_vault/blob/ce5fd488d13e36da4ed695a9bda8ef0427136f72/tests/data_manager.rs#L564)):*
> ```Rust
>                     test_utils::pub_appendable_data_version_up(&full_id, &ad, &mut rng);
>                 let new_data = Data::PubAppendable(new_appendable.clone());
>                 client.post(new_data);
> ```

The mechanism for posting appendable data is essentially the same as for structured data. It would be more interesting to test parallel `append`s, or both.

---

*[tests/data_manager.rs, line 580 at r3](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRiX3iBA6spZTPgynt5:-KRiX3iCrkxQt7Jdc2jw:bjw86di) ([raw file](https://github.com/maidsafe/safe_vault/blob/ce5fd488d13e36da4ed695a9bda8ef0427136f72/tests/data_manager.rs#L580)):*
> ```Rust
>                 match event {
>                     Event::Response { response: Response::PostSuccess(..), .. } => {
>                         // Only one client can succeed
> ```

It's possible that mroe than one succeeds; we just need to make sure that the `PostSuccess`es match with the stored data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/550)*

**Comment by afck** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tests/data_manager.rs, line 418 at r3](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRidq7MTJ9TEjpWSAuJ:-KRidq7NKLmR8iDx_eLp:b-8k7dmz) ([raw file](https://github.com/maidsafe/safe_vault/blob/ce5fd488d13e36da4ed695a9bda8ef0427136f72/tests/data_manager.rs#L418)):*
> ```Rust
>             let pointer = DataIdentifier::Structured(rng.gen(), 12345);
>             let appended_data = unwrap_result!(AppendedData::new(pointer, pub_key, &secret_key));
>             let wrapper = AppendWrapper::new_pub(*data.name(), appended_data.clone(), 0);
> ```

Shouldn't the version be `ad.version()` instead of `0`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/550)*

**Comment by maqi** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tests/data_manager.rs, line 564 at r3](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRiWs8TN6iokXjjBB_p:-KRiiqeEf9SowmT66wrZ:b3vhmx5) ([raw file](https://github.com/maidsafe/safe_vault/blob/ce5fd488d13e36da4ed695a9bda8ef0427136f72/tests/data_manager.rs#L564)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> The mechanism for posting appendable data is essentially the same as for structured data. It would be more interesting to test parallel `append`s, or both.
</details>
there is a separate parallel_append test

---

*[tests/data_manager.rs, line 580 at r3](https://reviewable.io:443/reviews/maidsafe/safe_vault/550#-KRiX3iBA6spZTPgynt5:-KRij0KpsODx7Tfhh3hD:b-t5pmzn) ([raw file](https://github.com/maidsafe/safe_vault/blob/ce5fd488d13e36da4ed695a9bda8ef0427136f72/tests/data_manager.rs#L580)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> It's possible that mroe than one succeeds; we just need to make sure that the `PostSuccess`es match with the stored data.
</details>
as different client is posting different data, only one shall succeed.
that true if different client posting same data, then more than one will success, but i don't think it needs to be covered here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/550)*

**Comment by afck** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/550)*

**Pull request merged**
