### PR TITLE
having message_id in Refresh message

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/413) &emsp; Multiple assignees:&emsp;@Fraser999&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/Fraser999">Fraser999</a>,&emsp;@brian-js&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/brian-js">brian-js</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/dirvine">dirvine</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
+@dirvine +@brian-js +@fraser999 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/413#-:-KF51dyUox3RO8lWA5H_:752104063)*

**Comment by maqi** [comment]
*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/413)*

**Comment by dirvine** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/413)*

**Pull request merged**
