### PR TITLE
Caching

### PR DESCRIPTION
**Pull request by madadam**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/505)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/cache.rs, line 55 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/505#-KKxUToEvzG2vRPA28tv:-KKxUToEvzG2vRPA28tw:-1034801576) ([raw file](https://github.com/maidsafe/safe_vault/blob/1eb76b65ca94e11cc7597cdf35c49796c0d3e8dc/src/cache.rs#L55)):*
> ```Rust
>     fn put(&self, response: Response) {
>         if let Response::GetSuccess(data, _) = response {
>             let _ = self.store.borrow_mut().insert(data.identifier(), data);
> ```

I don't think we should store structured data at all. I don't think there's a feasible mechanism to invalidate the cache in all affected nodes if the data is updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/505)*

**Comment by afck** [comment]
Reviewed 5 of 5 files at r2.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/505)*

**Comment by afck** [comment]
Reviewed 4 of 5 files at r3.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/505)*

**Comment by afck** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/505)*

**Pull request merged**
