### PR TITLE
PM updated for the new flow ; timed_buffer updated

### PR DESCRIPTION
**Pull request by maqi**
Affects: pmid_manager.rs vault.rs timed_buffer.rs

TimedBuffer updated to use HashMap
TimedBuffer provides new function of get_mut
TimedBuffer change get_expired to return key list
PM changed to use timed_buff
PM measure chunk by unit
PM accept post from DM: get_failure notification

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/393) &emsp; Multiple assignees:&emsp;@Fraser999&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/Fraser999">Fraser999</a>,&emsp;@brian-js&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/brian-js">brian-js</a>,&emsp;@dirvine&nbsp;<a href="/maidsafe/safe_vault/pulls/assigned/dirvine">dirvine</a>

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maqi** [comment]
+@dirvine +@brian-js +@fraser999 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-:-KE1o4eHbhI59Zxhp9M1:752104063)*

**Comment by Fraser999** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/timed_buffer.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE1wt_Jo67vrsi5o4dI:-KE1wt_Ksw6pys7SzGOx:-749776634) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/timed_buffer.rs#L44)):*
This function can be reduced to just:
```rust
pub fn get_mut(&mut self, key: &Key) -> Option<&mut Value> {
    self.map.get_mut(key).map(|&mut (ref mut value, ref mut time_stamp)| {
        *time_stamp = SteadyTime::now();
        value
    })
}
```

---

*[src/vault.rs, line 213 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE1y3QtIZTV4I6RQ5be:-KE1y3QtIZTV4I6RQ5bf:279234180) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/vault.rs#L213)):*
Why specify `Data::Immutable` here?  This could be `_` couldn't it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by maqi** [comment]
*[src/vault.rs, line 213 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE1y3QtIZTV4I6RQ5be:-KE1zMaUPqcHRHfUOLNU:-2002837778) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/vault.rs#L213)):*
Just in case we do want to explicitly show this is about immutable_data.
yes `_` is enough. and I am OK to both.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by dirvine** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/personas/pmid_manager.rs, line 41 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE2-QjJJ4hbf3jyAb9P:-KE2-QjJJ4hbf3jyAb9Q:-858720385) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L41)):*
Why impl Default instead of `fn new()` ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by dirvine** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/personas/pmid_manager.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE201ar0IynFttzGuyY:-KE201ar0IynFttzGuyZ:-1313858127) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L53)):*
Is it less confusing to perhaps have increment / decrement fn instead of put_data etc. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by maqi** [comment]
*[src/personas/pmid_manager.rs, line 41 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE2-QjJJ4hbf3jyAb9P:-KE23KEV1j5muAXuvo6R:-1143371044) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L41)):*
no idea. so `new()` is preferred here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by maqi** [comment]
*[src/personas/pmid_manager.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE201ar0IynFttzGuyY:-KE23WXRyFEkOXLLpC_g:1930277640) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L53)):*
this is to be consistent with the operation. also will be convenient if need to switch back to measure by size

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by maqi** [comment]
*[src/timed_buffer.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE1wt_Jo67vrsi5o4dI:-KE23pUfXri-0BSfDQZz:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/timed_buffer.rs#L44)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by dirvine** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/personas/pmid_manager.rs, line 41 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE2-QjJJ4hbf3jyAb9P:-KE249hyxkUX_E-QJ-ww:988645911) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L41)):*
IT seems more normal unless there is some overarching reason to have a type that needs a default setting. Here I think new is appropriate. 

---

*[src/personas/pmid_manager.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE201ar0IynFttzGuyY:-KE21k9RbhoBFetn7i83:1525748063) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L53)):*
So perhaps only thing in impl is a `new()` as `u64` defaults to 0 AFAIK. Then its a case of 
`account.stored().saturating_add()` etc. which is probably obvious. So we can refer to the two u64's direct with no impl ? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by dirvine** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/personas/pmid_manager.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE201ar0IynFttzGuyY:-KE24fKb2m7MbdFs_Ypo:1704857963) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L53)):*
Although if we have no impl (as per next comments) then just a default may be just OK here. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by dirvine** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/personas/pmid_manager.rs, line 41 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE2-QjJJ4hbf3jyAb9P:-KE25CO1N0ZsRHK8uA41:-452053722) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L41)):*
So all you need is 
`#[derive(Default)]` on the struct and we can access the members direct and no impl at all. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by maqi** [comment]
*[src/personas/pmid_manager.rs, line 41 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE2-QjJJ4hbf3jyAb9P:-KE25Xb-pI1aRqB6EhN-:-492619471) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L41)):*
ah, i remember previous we have a default allowance for account, which required by PM to issue an early alert.
If this impl doesn't cause any performance concern, can we leave as it is? as I think there might be soon a default function will be required, say an early alert IS needed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by maqi** [comment]
*[src/personas/pmid_manager.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE201ar0IynFttzGuyY:-KE26hbhcfZ0-KIUQhip:1186356259) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L53)):*
when we switch to measure by size and early alert, this function needs to return with bool. exposing two u64 won't be enough.
prefer not to do so

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by brian-js** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by dirvine** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/personas/pmid_manager.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE201ar0IynFttzGuyY:-KE2AxWfBFEU1BT16f5s:1802560039) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L53)):*
It's not by size though. If we switched then we would design and write the code for that beforehand. If this is as simple as possible just now then it will be easier in my opinion anyway. Otherwise we need to leave these functions, test them etc. without then the code is much smaller and cannot really be wrong AFAIK 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by dirvine** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/personas/pmid_manager.rs, line 41 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE2-QjJJ4hbf3jyAb9P:-KE2BPx8BB7PO-HLAnvh:-1657778548) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L41)):*
Yes leave default but use the macro instead of creating the code here. So Derive is cool for the struct. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by maqi** [comment]
*[src/vault.rs, line 213 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE1y3QtIZTV4I6RQ5be:-KE2F299LTB8qFlLOrd-:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/vault.rs#L213)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by maqi** [comment]
*[src/personas/pmid_manager.rs, line 41 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE2-QjJJ4hbf3jyAb9P:-KE2FnwbbPPyn99GSxwW:-499146009) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L41)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by maqi** [comment]
*[src/personas/pmid_manager.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/393#-KE201ar0IynFttzGuyY:-KE2Fu-zQh59zw5Pr-BX:1231408371) ([raw file](https://github.com/maidsafe/safe_vault/blob/435e4aaef83e4bad5f8b9fee5095f08de400f342/src/personas/pmid_manager.rs#L53)):*
but i don't think exposing two u64 is good. especially for the case like lost_data() (needs to update both two u64). exposing them means it totally leaves to the persona code to define the behaviour.
also, saturating_add won't add itself. so it will be something like `account.stored_place = account.stored_place.saturating_add(size)` in the persona code, which is not that nice

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by dirvine** [comment]
Reviewed 1 of 3 files at r1, 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Comment by dirvine** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_vault/393)*

**Pull request merged**
