### PR TITLE
fix/data_manager: send PutSuccess if immutable data exists

### PR DESCRIPTION
**Pull request by afck**
And exclude unneeded chunks from refresh.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_vault/462)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @Fraser999

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/462)*

**Comment by maqi** [comment]
*[src/personas/data_manager.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/462#-KGwQ_nqw22M-DJkvoFR:-KGwQ_nqw22M-DJkvoFS:975201839) ([raw file](https://github.com/maidsafe/safe_vault/blob/dec49b09137bdf85082b0a47daa9e5dcbd810c7d/src/personas/data_manager.rs#L154)):*
not sure about the future plan of Backup/Sacrificial copies,
but will using `match` will be safer ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/462)*

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/personas/data_manager.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_vault/462#-KGwQ_nqw22M-DJkvoFR:-KGwTJJQjYHJ8hkVmiI5:-905306415) ([raw file](https://github.com/maidsafe/safe_vault/blob/dec49b09137bdf85082b0a47daa9e5dcbd810c7d/src/personas/data_manager.rs#L154)):*
Good point!
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/462)*

**Comment by maqi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_vault/462)*

**Pull request merged**
